import React, { useState } from 'react';
import { 
  FileCode, 
  Copy, 
  Check, 
  Download, 
  Terminal, 
  Sparkles, 
  Send, 
  Cpu, 
  Code2 
} from 'lucide-react';
import { BettingStrategy, StakeApiCredentials } from '../types';

interface ScriptExporterProps {
  strategy: BettingStrategy;
  credentials: StakeApiCredentials;
  currency: string;
}

export const ScriptExporter: React.FC<ScriptExporterProps> = ({
  strategy,
  credentials,
  currency,
}) => {
  const [activeLang, setActiveLang] = useState<'python' | 'node' | 'tampermonkey'>('python');
  const [copied, setCopied] = useState(false);

  // Generate Python Telegram Bot script tailored to current strategy
  const pythonScript = `"""
========================================================================
 Stake.com Originals Auto-Betting & Telegram Controller Bot
 Generated by Stake Bot Engine (Gemini 3.7 AI & Provably Fair Matrix)
========================================================================
Installation:
  pip install python-telegram-bot requests aiohttp python-dotenv
"""

import os
import time
import json
import asyncio
import logging
import requests
from telegram import Update, InlineKeyboardButton, InlineKeyboardMarkup
from telegram.ext import Application, CommandHandler, CallbackQueryHandler, ContextTypes

# ================= CONFIGURATION =================
TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN", "VOTRE_BOT_TOKEN_ICI")
STAKE_API_KEY = os.getenv("STAKE_API_KEY", "${credentials.apiKey || 'VOTRE_CLE_API_STAKE'}")
STAKE_DOMAIN = "${credentials.domain || 'stake.com'}"
CURRENCY = "${currency}"

# Paramètres de la stratégie active (${strategy.name})
GAME = "${strategy.game}"
BASE_BET = ${strategy.baseBet}
TARGET_MULTIPLIER = ${strategy.targetMultiplier}
ON_LOSS_ACTION = "${strategy.onLossAction}"  # multiply, increase_fixed, reset
ON_LOSS_VALUE = ${strategy.onLossValue || 2.0}
STOP_LOSS = ${strategy.stopOnLoss || 20.0}
TAKE_PROFIT = ${strategy.stopOnProfit || 15.0}
MAX_CONSECUTIVE_LOSSES = ${strategy.maxConsecutiveLosses || 8}

# Variables d'état
autobet_running = False
current_bet = BASE_BET
session_profit = 0.0
total_bets = 0
wins = 0
losses = 0
consecutive_losses = 0

logging.basicConfig(format='%(asctime)s - %(name)s - %(levelname)s - %(message)s', level=logging.INFO)

# ================= GRAPHQL STAKE API CLIENT =================
def execute_stake_bet(amount, target_mult):
    """Envoie une mutation GraphQL officielle à Stake.com pour placer une mise."""
    url = f"https://{STAKE_DOMAIN}/_api/graphql"
    headers = {
        "x-access-token": STAKE_API_KEY,
        "content-type": "application/json",
        "user-agent": "Mozilla/5.0 StakeTelegramBot/1.0"
    }

    # Exemple pour Dice (adapter selon le jeu)
    query = """
    mutation DiceRoll($amount: Float!, $target: Float!, $condition: CasinoGameDiceConditionEnum!, $currency: CurrencyEnum!) {
        diceRoll(amount: $amount, target: $target, condition: $condition, currency: $currency) {
            id
            payoutMultiplier
            payout
            state {
                ... on CasinoGameDice {
                    result
                    target
                    condition
                }
            }
        }
    }
    """
    payload = {
        "query": query,
        "variables": {
            "amount": amount,
            "target": 50.49 if target_mult == 2.0 else round(99.0 / target_mult, 2),
            "condition": "above",
            "currency": CURRENCY.lower()
        }
    }
    
    try:
        response = requests.post(url, json=payload, headers=headers, timeout=10)
        return response.json()
    except Exception as e:
        logging.error(f"Erreur API Stake: {e}")
        return None


# ================= TELEGRAM HANDLERS =================
async def start_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    keyboard = [
        [InlineKeyboardButton("🚀 Démarrer Auto-Bet", callback_data="start_autobet")],
        [InlineKeyboardButton("🛑 Arrêter", callback_data="stop_autobet"), InlineKeyboardButton("📊 Statistiques", callback_data="get_stats")]
    ]
    reply_markup = InlineKeyboardMarkup(keyboard)
    await update.message.reply_text(
        f"🤖 *Stake Strategy Bot Connecté !*\\n\\n"
        f"• Jeu: *{GAME.upper()}*\\n"
        f"• Stratégie: *${strategy.name}*\\n"
        f"• Mise de base: *{BASE_BET} {CURRENCY}*\\n"
        f"• Multiplicateur: *{TARGET_MULTIPLIER}x*\\n\\n"
        f"Cliquez ci-dessous pour contrôler le bot.",
        reply_markup=reply_markup,
        parse_mode="Markdown"
    )

async def stats_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    wr = (wins / total_bets * 100) if total_bets > 0 else 0.0
    await update.message.reply_text(
        f"📊 *Bilan de Session Stake*\\n\\n"
        f"💰 *Profit Net:* {'+' if session_profit >= 0 else ''}{session_profit:.4f} {CURRENCY}\\n"
        f"🎯 *Taux de Victoire:* {wr:.1f}% ({wins}W / {losses}L)\\n"
        f"🎲 *Total Paris:* {total_bets}\\n"
        f"⚠️ *Pertes d'affilée actuelles:* {consecutive_losses}",
        parse_mode="Markdown"
    )

async def stop_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    global autobet_running
    autobet_running = False
    await update.message.reply_text("🛑 *Auto-bet interrompu immédiatement.*", parse_mode="Markdown")

def main():
    app = Application.builder().token(TELEGRAM_BOT_TOKEN).build()
    app.add_handler(CommandHandler("start", start_command))
    app.add_handler(CommandHandler("stats", stats_command))
    app.add_handler(CommandHandler("stop", stop_command))
    
    print("🚀 Stake Telegram Bot démarré avec succès...")
    app.run_polling()

if __name__ == "__main__":
    main()
`;

  // Generate Node.js script
  const nodeScript = `/**
 * Stake.com Node.js Auto-Betting Engine & Telegram Bridge
 */
import fetch from 'node-fetch';

const STAKE_API_KEY = process.env.STAKE_API_KEY || "${credentials.apiKey || ''}";
const TELEGRAM_BOT_TOKEN = process.env.TELEGRAM_BOT_TOKEN || "";
const CHAT_ID = process.env.TELEGRAM_CHAT_ID || "";

const STRATEGY = {
  game: "${strategy.game}",
  baseBet: ${strategy.baseBet},
  targetMultiplier: ${strategy.targetMultiplier},
  stopLoss: ${strategy.stopOnLoss || 20},
  takeProfit: ${strategy.stopOnProfit || 15},
  onLossMultiply: ${strategy.onLossValue || 2.0},
};

let currentBet = STRATEGY.baseBet;
let totalProfit = 0;

async function sendTelegramAlert(text) {
  if (!TELEGRAM_BOT_TOKEN || !CHAT_ID) return;
  await fetch(\`https://api.telegram.org/bot\${TELEGRAM_BOT_TOKEN}/sendMessage\`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ chat_id: CHAT_ID, text, parse_mode: 'Markdown' })
  });
}

console.log("⚡ Stake Engine Node.js Prêt pour", STRATEGY.game);
`;

  const activeContent = activeLang === 'python' ? pythonScript : activeLang === 'node' ? nodeScript : pythonScript;

  const handleCopy = () => {
    navigator.clipboard.writeText(activeContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const filename = activeLang === 'python' ? 'stake_telegram_bot.py' : 'stake_bot.js';
    const blob = new Blob([activeContent], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div id="script-exporter-panel" className="bg-slate-900 border border-slate-800 rounded-2xl p-5 shadow-sm space-y-5">
      
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pb-4 border-b border-slate-800">
        <div>
          <h3 className="text-base font-bold text-white tracking-tight flex items-center gap-2">
            <FileCode className="w-4 h-4 text-amber-400" />
            Exportateur de Scripts Python & Node.js
          </h3>
          <p className="text-xs text-slate-400 mt-0.5">
            Code source autonome prêt pour hébergement VPS, Serveur Dédié ou Exécution Locale 24/7.
          </p>
        </div>

        {/* Language Tabs & Actions */}
        <div className="flex items-center gap-2">
          <div className="flex items-center bg-slate-950 p-1 rounded-xl border border-slate-800 text-xs">
            <button
              onClick={() => setActiveLang('python')}
              className={`px-3 py-1 rounded-lg font-semibold transition ${
                activeLang === 'python'
                  ? 'bg-amber-600 text-white shadow-sm'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              Python (.py)
            </button>
            <button
              onClick={() => setActiveLang('node')}
              className={`px-3 py-1 rounded-lg font-semibold transition ${
                activeLang === 'node'
                  ? 'bg-blue-600 text-white shadow-sm'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              Node.js (.js)
            </button>
          </div>

          <button
            onClick={handleCopy}
            className="px-3 py-1.5 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-semibold border border-slate-700 transition flex items-center gap-1.5"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
            <span>{copied ? 'Copié !' : 'Copier'}</span>
          </button>

          <button
            onClick={handleDownload}
            className="px-3 py-1.5 rounded-xl bg-amber-600 hover:bg-amber-500 text-white text-xs font-semibold shadow-md transition flex items-center gap-1.5"
          >
            <Download className="w-3.5 h-3.5" />
            <span>Télécharger</span>
          </button>
        </div>
      </div>

      {/* Code Viewer */}
      <div className="relative rounded-xl overflow-hidden border border-slate-800 bg-slate-950">
        <div className="bg-slate-900/80 px-4 py-2 border-b border-slate-800 text-xs font-mono text-slate-400 flex items-center justify-between">
          <span className="flex items-center gap-2">
            <Terminal className="w-3.5 h-3.5 text-amber-400" />
            {activeLang === 'python' ? 'stake_telegram_bot.py' : 'stake_bot.js'}
          </span>
          <span className="text-[10px] text-slate-500">
            {activeContent.split('\n').length} lignes
          </span>
        </div>

        <pre className="p-4 text-xs font-mono text-slate-300 overflow-x-auto max-h-[420px] leading-relaxed select-all">
          <code>{activeContent}</code>
        </pre>
      </div>

    </div>
  );
};
