import { BettingStrategy } from '../types';
import { generateStakeDiceMultiConditionStrategy } from './constructiveStrategies';

export const PREDEFINED_STRATEGIES: BettingStrategy[] = [
  // ==========================================
  // DICE STRATEGIES
  // ==========================================
  {
    id: 'strat-dice-oscars-grind',
    name: "Oscar's Grind Constructif (Dice 2.0x)",
    game: 'dice',
    description: "Méthode constructive reine : objectif de +1 unité de profit net par cycle. Mise constante sur chaque défaite (JAMAIS de doublement sur perte !). La mise n'augmente d'1 unité que lors des victoires pour clore le cycle à +1 unité, puis réinitialisation.",
    riskLevel: 'low',
    baseBet: 0.20,
    currency: 'USDT',
    targetMultiplier: 2.0,
    winChance: 49.50,
    gameConfig: {
      diceCondition: 'above',
      diceTarget: 50.49,
    },
    onWinAction: 'increase_fixed',
    onWinValue: 0.20,
    onLossAction: 'custom',
    onLossValue: 0,
    stopOnProfit: 10.0,
    stopOnLoss: 20.0,
    maxBetLimit: 2.0,
    maxConsecutiveLosses: 10,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: "Stratégie hautement résiliente : contrairement à la Martingale, les pertes ne gonflent pas la mise. L'accumulation de petits profits se fait sans stress sur le capital."
  },
  {
    id: 'strat-dice-dalembert',
    name: "D'Alembert Linéaire Équilibré (Dice 2.10x)",
    game: 'dice',
    description: "Système d'équilibre mathématique : ajoute 1 petite unité (+0.10 USDT) après chaque perte et soustrait 1 unité après chaque gain. Évite tout emballement géométrique.",
    riskLevel: 'low',
    baseBet: 0.20,
    currency: 'USDT',
    targetMultiplier: 2.10,
    winChance: 47.14,
    gameConfig: {
      diceCondition: 'above',
      diceTarget: 52.85,
    },
    onWinAction: 'custom',
    onLossAction: 'increase_fixed',
    onLossValue: 0.10,
    stopOnProfit: 12.0,
    stopOnLoss: 20.0,
    maxBetLimit: 2.50,
    maxConsecutiveLosses: 10,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: "Plus doux et plus sécurisant que les progressions géométriques, D'Alembert permet de sortir positif même avec un nombre de victoires légèrement inférieur aux défaites."
  },
  {
    id: 'strat-dice-1326-milestone',
    name: 'Système 1-3-2-6 Milestone Lock (Dice 2.0x)',
    game: 'dice',
    description: "Progression par palier sur 4 victoires consécutives (1x, 3x, 2x, 6x). En cas de perte, retour immédiat à 1 unité. Les gains sont verrouillés dès le 2ème palier gagné (+2 unités sécurisées).",
    riskLevel: 'medium',
    baseBet: 0.25,
    currency: 'USDT',
    targetMultiplier: 2.0,
    winChance: 49.50,
    gameConfig: {
      diceCondition: 'above',
      diceTarget: 50.49,
    },
    onWinAction: 'increase_pct',
    onWinValue: 50,
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 15.0,
    stopOnLoss: 15.0,
    maxBetLimit: 2.50,
    maxConsecutiveLosses: 8,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: "Offre un potentiel d'explosion de capital (+12 unités sur 4 victoires) avec un risque réel maximal de seulement 2 unités tirées du capital propre."
  },
  {
    id: 'strat-dice-high-prob-scalper',
    name: 'Scalper Haute Probabilité (Dice 1.20x - 82.5% Win)',
    game: 'dice',
    description: "Scalping à très haute fréquence : taux de réussite de 82.50%. Mise constante avec réévaluation du capital par palier de 20 lancers et stop-loss strict.",
    riskLevel: 'ultra_safe',
    baseBet: 0.50,
    currency: 'USDT',
    targetMultiplier: 1.20,
    winChance: 82.50,
    gameConfig: {
      diceCondition: 'above',
      diceTarget: 17.50,
    },
    onWinAction: 'reset',
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 8.0,
    stopOnLoss: 15.0,
    maxBetLimit: 2.0,
    maxConsecutiveLosses: 3,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: "Maximise la régularité et minimise les drawdowns. Idéal pour les objectifs de profit constants et le farming VIP."
  },
  {
    id: 'strat-dice-fibonacci-doux',
    name: 'Fibonacci Doux Constructif (Dice 2.0x)',
    game: 'dice',
    description: "Suite arithmétique 1-1-2-3-5 sur pertes. En cas de victoire, recul de 2 crans dans la séquence pour sécuriser les gains précédents sans jamais risquer d'emballement exponentiel.",
    riskLevel: 'low',
    baseBet: 0.20,
    currency: 'USDT',
    targetMultiplier: 2.0,
    winChance: 49.50,
    gameConfig: {
      diceCondition: 'above',
      diceTarget: 50.49,
    },
    onWinAction: 'custom',
    onLossAction: 'fibonacci',
    onLossValue: 1.5,
    stopOnProfit: 12.0,
    stopOnLoss: 18.0,
    maxBetLimit: 3.0,
    maxConsecutiveLosses: 7,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: "La progression de Fibonacci amortit la variance naturelle du Dice et permet de récupérer le cumul des pertes avec seulement 2 victoires partielles."
  },
  {
    id: 'strat-dice-fractional-kelly',
    name: 'Fractional Kelly Scalper (Dice 1.40x - 70.7% Win)',
    game: 'dice',
    description: "Dimensionnement optimal selon 25% du critère de Kelly. Cote cible de 1.40x avec 70.71% de chances de gain. Croissance logarithmique maximale avec un risque de ruine quasi-nul.",
    riskLevel: 'low',
    baseBet: 0.40,
    currency: 'USDT',
    targetMultiplier: 1.40,
    winChance: 70.71,
    gameConfig: {
      diceCondition: 'above',
      diceTarget: 29.29,
    },
    onWinAction: 'reset',
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 10.0,
    stopOnLoss: 15.0,
    maxBetLimit: 1.50,
    maxConsecutiveLosses: 5,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: "Le critère de Kelly fractionnaire assure l'espérance de croissance la plus stable du solde sans jamais surexposer la bankroll."
  },
  {
    id: 'strat-dice-vip-farming',
    name: 'VIP Wager & Rakeback Farmer (Dice 1.0102x - 98% Win)',
    game: 'dice',
    description: "Mise plate ultra-défensive sur 98% de chances de gain (Roll > 1.00). Spécifiquement conçu pour générer du volume de mise (wager) et débloquer les bonus VIP Stake avec un drawdown minimal.",
    riskLevel: 'ultra_safe',
    baseBet: 1.00,
    currency: 'USDT',
    targetMultiplier: 1.0102,
    winChance: 98.00,
    gameConfig: {
      diceCondition: 'above',
      diceTarget: 1.99,
    },
    onWinAction: 'reset',
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 15.0,
    stopOnLoss: 25.0,
    maxBetLimit: 2.00,
    maxConsecutiveLosses: 2,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: "Volume massif avec 98% de tirages gagnants. Idéal pour le farming de points VIP et de rakeback régulier."
  },
  {
    id: 'strat-dice-asymmetric-moonshot',
    name: 'Asymmetric Moonshot 50x (Dice 50.0x - 1.98% Win)',
    game: 'dice',
    description: "Chasse aux gros multiplicateurs avec micro-mises fixes (0.05% de bankroll). Un seul lancer gagnant rapporte +50 unités et compense immédiatement les séries négatives.",
    riskLevel: 'medium',
    baseBet: 0.05,
    currency: 'USDT',
    targetMultiplier: 50.0,
    winChance: 1.98,
    gameConfig: {
      diceCondition: 'above',
      diceTarget: 98.01,
    },
    onWinAction: 'reset',
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 25.0,
    stopOnLoss: 10.0,
    maxBetLimit: 0.20,
    maxConsecutiveLosses: 80,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: "Asymétrie positive pure : perte unitaire négligeable pour un gain ponctuel massif qui verrouille l'objectif de session."
  },

  // ==========================================
  // LIMBO STRATEGIES
  // ==========================================
  {
    id: 'strat-limbo-paroli-lock',
    name: 'Paroli 1-2-4 Profit-Lock (Limbo 2.0x)',
    game: 'limbo',
    description: 'Anti-Martingale positive : mise plate en cas de défaite. En cas de gain, on capitalise sur la série pour 3 coups consécutifs (1x -> 2x -> 4x), puis encaissement total des bénéfices (+7 unités) et retour à la base.',
    riskLevel: 'medium',
    baseBet: 0.25,
    currency: 'USDT',
    targetMultiplier: 2.0,
    winChance: 49.50,
    gameConfig: {
      limboTarget: 2.0,
    },
    onWinAction: 'increase_pct',
    onWinValue: 100,
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 15.0,
    stopOnLoss: 15.0,
    maxBetLimit: 2.0,
    maxConsecutiveLosses: 8,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: 'Risque maximal limité à la mise unitaire de 0.25 USDT. Les bénéfices explosent lors des séries favorables sans jamais risquer de ruine sur les pertes.'
  },
  {
    id: 'strat-limbo-fractional-kelly',
    name: 'Fractional Kelly Scalper (Limbo 1.35x)',
    game: 'limbo',
    description: 'Scalping quantitatif à haute probabilité (73.33% de chances de gain). Mise calibrée selon 25% du critère de Kelly pour une croissance régulière et une variance minimale.',
    riskLevel: 'low',
    baseBet: 0.50,
    currency: 'USDT',
    targetMultiplier: 1.35,
    winChance: 73.33,
    gameConfig: {
      limboTarget: 1.35,
    },
    onWinAction: 'reset',
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 10.0,
    stopOnLoss: 15.0,
    maxBetLimit: 2.0,
    maxConsecutiveLosses: 4,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: 'Le critère de Kelly fractionnaire assure une espérance de croissance optimale du capital en minimisant drastiquement le risque de drawdown.'
  },
  {
    id: 'strat-limbo-multi-target-sniper',
    name: 'Sniper Multiplicateur Asymétrique (Limbo 5.0x)',
    game: 'limbo',
    description: 'Recherche de multiplicateurs 5.0x (19.8% win chance) à micro-mises fixes. Encaissement dès le 1er multiplicateur touché avec reset immédiat.',
    riskLevel: 'medium',
    baseBet: 0.10,
    currency: 'USDT',
    targetMultiplier: 5.0,
    winChance: 19.80,
    gameConfig: {
      limboTarget: 5.0,
    },
    onWinAction: 'reset',
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 15.0,
    stopOnLoss: 10.0,
    maxBetLimit: 0.50,
    maxConsecutiveLosses: 25,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: 'Ratio risque/bénéfice asymétrique : un seul succès compense 5 lancers et produit un bénéfice net immédiat.'
  },
  {
    id: 'strat-limbo-oscars-grind',
    name: "Oscar's Grind Limbo (Limbo 2.0x)",
    game: 'limbo',
    description: "Application d'Oscar's Grind sur Limbo 2.0x : mise gelée après chaque perte. Augmentation d'une seule unité lors d'un gain jusqu'à clore le cycle à +1 unité nette.",
    riskLevel: 'low',
    baseBet: 0.20,
    currency: 'USDT',
    targetMultiplier: 2.0,
    winChance: 49.50,
    gameConfig: {
      limboTarget: 2.0,
    },
    onWinAction: 'increase_fixed',
    onWinValue: 0.20,
    onLossAction: 'custom',
    onLossValue: 0,
    stopOnProfit: 10.0,
    stopOnLoss: 18.0,
    maxBetLimit: 2.0,
    maxConsecutiveLosses: 9,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: 'Zéro stress sur les mauvaises passes : le capital ne subit aucune dégradation rapide car la mise ne gonfle jamais sur les pertes.'
  },
  {
    id: 'strat-limbo-high-roller-scalp',
    name: 'High-Roller Scalp 1.10x (Limbo 90% Win)',
    game: 'limbo',
    description: 'Scalping ultra-sûr visant 1.10x (90.00% de winrate). Objectif de +5% de capital par session avec mise plate et réinitialisation systématique.',
    riskLevel: 'ultra_safe',
    baseBet: 0.80,
    currency: 'USDT',
    targetMultiplier: 1.10,
    winChance: 90.00,
    gameConfig: {
      limboTarget: 1.10,
    },
    onWinAction: 'reset',
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 8.0,
    stopOnLoss: 12.0,
    maxBetLimit: 2.50,
    maxConsecutiveLosses: 3,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: 'Régularité maximale avec 9 tirages sur 10 gagnants. Parfait pour les profils prudents cherchant une progression tranquille.'
  },
  {
    id: 'strat-limbo-moonshot-50x',
    name: 'Limbo Rocket Moonshot 50x (Limbo 50.0x)',
    game: 'limbo',
    description: 'Chasse aux fusées 50x avec micro-mises 0.05% de bankroll. Conçu pour encaisser des hausses exponentielles sans entamer le capital de base.',
    riskLevel: 'medium',
    baseBet: 0.05,
    currency: 'USDT',
    targetMultiplier: 50.0,
    winChance: 1.98,
    gameConfig: {
      limboTarget: 50.0,
    },
    onWinAction: 'reset',
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 25.0,
    stopOnLoss: 10.0,
    maxBetLimit: 0.20,
    maxConsecutiveLosses: 80,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: 'Les multiplicateurs Limbo montent jusqu’à 1,000,000x : viser 50x offre un compromis fréquence/gain idéal avec micro-mise.'
  },
  {
    id: 'strat-limbo-dynamic-paliers',
    name: 'Limbo Paliers 1.50x (66% Win)',
    game: 'limbo',
    description: 'Cible 1.50x avec un cycle de 2 victoires successives. Dès 2 succès consécutifs, encaissement de +1.25 unités et réinitialisation.',
    riskLevel: 'low',
    baseBet: 0.35,
    currency: 'USDT',
    targetMultiplier: 1.50,
    winChance: 66.00,
    gameConfig: {
      limboTarget: 1.50,
    },
    onWinAction: 'increase_pct',
    onWinValue: 50,
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 12.0,
    stopOnLoss: 15.0,
    maxBetLimit: 2.0,
    maxConsecutiveLosses: 6,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: '2 chances sur 3 de victoire à chaque tirage : sécuriser le profit après 2 victoires maximise le taux de conversion de session.'
  },

  // ==========================================
  // MINES STRATEGIES
  // ==========================================
  {
    id: 'strat-mines-1mine-safe-hunter',
    name: 'Mines 1-Mine Safe Hunter (88% Probabilité)',
    game: 'mines',
    description: 'Grille avec 1 seule mine sur 25 cases (24 diamants). Encaissement sécurisé à 3 diamants (x1.18). Probabilité de réussite de 88.00%. En cas de défaite rare, récupération par palier doux.',
    riskLevel: 'ultra_safe',
    baseBet: 1.00,
    currency: 'USDT',
    targetMultiplier: 1.18,
    winChance: 88.00,
    gameConfig: {
      minesCount: 1,
      minesGemsToCashout: 3,
      minesChosenTiles: [4, 12, 20],
    },
    onWinAction: 'reset',
    onLossAction: 'increase_pct',
    onLossValue: 15,
    stopOnProfit: 10.0,
    stopOnLoss: 15.0,
    maxBetLimit: 5.0,
    maxConsecutiveLosses: 3,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: 'Taux de gain très élevé (88%), idéal pour les sessions calmes à faible risque et l’accumulation régulière de micro-bénéfices.'
  },
  {
    id: 'strat-mines-3gem-fibonacci',
    name: 'Mines 3-Gem Fibonacci Constructif',
    game: 'mines',
    description: 'Grille 3 mines, encaissement automatique à 3 diamants (x1.74). Progression douce basée sur la suite arithmétique de Fibonacci pour une récupération fluide sans explosion de mise.',
    riskLevel: 'low',
    baseBet: 0.20,
    currency: 'USDT',
    targetMultiplier: 1.74,
    winChance: 56.88,
    gameConfig: {
      minesCount: 3,
      minesGemsToCashout: 3,
      minesChosenTiles: [0, 6, 12],
    },
    onWinAction: 'reset',
    onLossAction: 'fibonacci',
    onLossValue: 1.5,
    stopOnProfit: 12.0,
    stopOnLoss: 20.0,
    maxBetLimit: 5.0,
    maxConsecutiveLosses: 6,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: 'La suite de Fibonacci réduit la violence de la variance et permet de récupérer le cumul des pertes avec deux succès successifs.'
  },
  {
    id: 'strat-mines-5mines-cashout2',
    name: 'Mines 5-Mines Sniper 2-Diamants (x1.75)',
    game: 'mines',
    description: 'Grille avec 5 mines et encaissement strict dès le 2ème diamant découvert (x1.75). Excellente dynamique pour les cycles de profit rapide.',
    riskLevel: 'medium',
    baseBet: 0.30,
    currency: 'USDT',
    targetMultiplier: 1.75,
    winChance: 57.0,
    gameConfig: {
      minesCount: 5,
      minesGemsToCashout: 2,
      minesChosenTiles: [2, 14],
    },
    onWinAction: 'reset',
    onLossAction: 'increase_fixed',
    onLossValue: 0.10,
    stopOnProfit: 15.0,
    stopOnLoss: 15.0,
    maxBetLimit: 3.0,
    maxConsecutiveLosses: 6,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: 'Cible un multiplicateur solide avec seulement 2 clics par round, réduisant drastiquement l’exposition au risque.'
  },
  {
    id: 'strat-mines-1mine-ultra-scalper',
    name: '1-Mine Ultra Scalper (1 Diamant - 96% Winrate x1.03)',
    game: 'mines',
    description: 'Grille 1 mine avec encaissement instantané dès le 1er diamant cliqué (x1.03). Probabilité mathématique de 96.00%. Cadence ultra-rapide sans Martingale.',
    riskLevel: 'ultra_safe',
    baseBet: 1.50,
    currency: 'USDT',
    targetMultiplier: 1.03,
    winChance: 96.00,
    gameConfig: {
      minesCount: 1,
      minesGemsToCashout: 1,
      minesChosenTiles: [12],
    },
    onWinAction: 'reset',
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 8.0,
    stopOnLoss: 15.0,
    maxBetLimit: 4.0,
    maxConsecutiveLosses: 2,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: 'Probabilité écrasante de 24 sur 25 (96%). Idéal pour sécuriser quelques unités rapidement avec une variance minimale.'
  },
  {
    id: 'strat-mines-2mines-balanced',
    name: '2-Mines Balanced Growth (4 Diamants - x2.00)',
    game: 'mines',
    description: 'Grille 2 mines, encaissement automatique à 4 diamants (cote exacte 2.00x). Gestion par cycle de profit avec remise à la base.',
    riskLevel: 'low',
    baseBet: 0.30,
    currency: 'USDT',
    targetMultiplier: 2.00,
    winChance: 49.50,
    gameConfig: {
      minesCount: 2,
      minesGemsToCashout: 4,
      minesChosenTiles: [0, 4, 20, 24],
    },
    onWinAction: 'reset',
    onLossAction: 'increase_fixed',
    onLossValue: 0.05,
    stopOnProfit: 15.0,
    stopOnLoss: 18.0,
    maxBetLimit: 2.50,
    maxConsecutiveLosses: 7,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: 'Fournit un multiplicateur 2.0x propre et équilibré en exploitant les 4 coins de la grille avec seulement 2 mines dispersées.'
  },
  {
    id: 'strat-mines-8mines-quick-strike',
    name: '8-Mines Quick Strike 1-Gem (x1.45 - 68% Win)',
    game: 'mines',
    description: 'Grille 8 mines, encaissement dès le 1er clic (17 diamants sur 25, gain net +45%). Rotation sur 1 seul clic par manche.',
    riskLevel: 'medium',
    baseBet: 0.40,
    currency: 'USDT',
    targetMultiplier: 1.45,
    winChance: 68.00,
    gameConfig: {
      minesCount: 8,
      minesGemsToCashout: 1,
      minesChosenTiles: [7],
    },
    onWinAction: 'reset',
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 12.0,
    stopOnLoss: 15.0,
    maxBetLimit: 2.0,
    maxConsecutiveLosses: 5,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: 'Un seul clic puissant pour sortir immédiatement à 1.45x sans jamais s’exposer aux ouvertures multiples.'
  },
  {
    id: 'strat-mines-24mines-moonshot',
    name: '24-Mines Single Gem Moonshot (x24.75)',
    game: 'mines',
    description: 'Grille extrême avec 24 mines et 1 seule gemme libre (multiplicateur x24.75 sur un seul clic). Micro-mise 0.02% de bankroll pour capter les jackpots ponctuels.',
    riskLevel: 'high',
    baseBet: 0.05,
    currency: 'USDT',
    targetMultiplier: 24.75,
    winChance: 4.00,
    gameConfig: {
      minesCount: 24,
      minesGemsToCashout: 1,
      minesChosenTiles: [12],
    },
    onWinAction: 'reset',
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 25.0,
    stopOnLoss: 10.0,
    maxBetLimit: 0.15,
    maxConsecutiveLosses: 50,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: 'Asymétrie positive maximale : 1 succès rapporte 24.75x la mise, finançant facilement 30 à 40 tentatives à micro-coût.'
  },

  // ==========================================
  // PLINKO STRATEGIES
  // ==========================================
  {
    id: 'strat-plinko-pyramid-balance',
    name: 'Plinko 14 Rangées Volatility Cushion (x55 Max)',
    game: 'plinko',
    description: 'Plinko 14 rangées en risque Moyen (multiplicateurs jusqu’à 55x). Mise fixe sans augmentation avec gestion par cycle de 200 lancers.',
    riskLevel: 'low',
    baseBet: 0.10,
    currency: 'USDT',
    targetMultiplier: 4.0,
    winChance: 28.5,
    gameConfig: {
      plinkoRows: 14,
      plinkoRisk: 'medium',
    },
    onWinAction: 'reset',
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 15.0,
    stopOnLoss: 15.0,
    maxBetLimit: 1.0,
    maxConsecutiveLosses: 40,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: 'Les multiplicateurs intermédiaires (1.9x, 4x, 11x) financent les tirages tout en maintenant une exposition très basse par bille.'
  },
  {
    id: 'strat-plinko-16rows-high-hunter',
    name: 'Plinko 16 Rangées High Risk Hunter (x1000 Max)',
    game: 'plinko',
    description: 'Plinko 16 rangées en risque Élevé (High). Micro-mise calibrée pour 1000 billes afin de viser les multiplicateurs extrêmes (26x, 130x et 1000x).',
    riskLevel: 'high',
    baseBet: 0.05,
    currency: 'USDT',
    targetMultiplier: 26.0,
    winChance: 9.5,
    gameConfig: {
      plinkoRows: 16,
      plinkoRisk: 'high',
    },
    onWinAction: 'reset',
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 25.0,
    stopOnLoss: 20.0,
    maxBetLimit: 0.20,
    maxConsecutiveLosses: 60,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: 'Les multiplicateurs rares mais gigantesques (x26 à x1000) offrent un profil d’asymétrie convexe optimal avec une micro-mise unitaire.'
  },
  {
    id: 'strat-plinko-8rows-low-scalp',
    name: 'Plinko 8 Rangées Low Risk Scalping (x5.6 Max)',
    game: 'plinko',
    description: 'Plinko 8 rangées en risque Faible (Low). Multiplicateur central de 0.5x à 5.6x aux bords. Variance minimale pour des sessions sans secousses.',
    riskLevel: 'ultra_safe',
    baseBet: 0.30,
    currency: 'USDT',
    targetMultiplier: 1.5,
    winChance: 65.0,
    gameConfig: {
      plinkoRows: 8,
      plinkoRisk: 'low',
    },
    onWinAction: 'reset',
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 10.0,
    stopOnLoss: 15.0,
    maxBetLimit: 1.50,
    maxConsecutiveLosses: 15,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: 'Les paniers centraux remboursent la majeure partie de la mise (0.9x à 1.1x), évitant tout décrochage brutal de bankroll.'
  },
  {
    id: 'strat-plinko-12rows-medium',
    name: 'Plinko 12 Rangées Medium Balance (x33 Max)',
    game: 'plinko',
    description: 'Configuration 12 rangées en risque Moyen. Compromis idéal pour accumuler des gains réguliers avec des pointes fréquentes à 4x et 11x.',
    riskLevel: 'low',
    baseBet: 0.15,
    currency: 'USDT',
    targetMultiplier: 3.0,
    winChance: 35.0,
    gameConfig: {
      plinkoRows: 12,
      plinkoRisk: 'medium',
    },
    onWinAction: 'reset',
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 12.0,
    stopOnLoss: 15.0,
    maxBetLimit: 1.00,
    maxConsecutiveLosses: 30,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: 'Distribution de Gauss resserrée : les billes tombent souvent dans les paniers rentables 1.6x et 3x pour un solde stable.'
  },
  {
    id: 'strat-plinko-16rows-low-vip',
    name: 'Plinko 16 Rangées Low Risk VIP Volume (x16 Max)',
    game: 'plinko',
    description: 'Plinko 16 rangées Low Risk pour du farming de volume VIP. Les billes restent concentrées entre 0.5x et 2x avec 99% de RTP continu.',
    riskLevel: 'ultra_safe',
    baseBet: 0.50,
    currency: 'USDT',
    targetMultiplier: 1.4,
    winChance: 70.0,
    gameConfig: {
      plinkoRows: 16,
      plinkoRisk: 'low',
    },
    onWinAction: 'reset',
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 10.0,
    stopOnLoss: 20.0,
    maxBetLimit: 2.0,
    maxConsecutiveLosses: 20,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: 'Parfait pour faire tourner un gros volume de wagers sans subir de chute rapide de solde.'
  },

  // ==========================================
  // KENO STRATEGIES
  // ==========================================
  {
    id: 'strat-keno-4hits-asymmetric',
    name: 'Keno 4-Hits Asymmetric Yield (x90 Max)',
    game: 'keno',
    description: 'Sélection de 4 numéros clés (gain à partir de 2 numéros, jackpot à 4 numéros 90x). Gestion par cycle sans emballement.',
    riskLevel: 'medium',
    baseBet: 0.20,
    currency: 'USDT',
    targetMultiplier: 4.0,
    winChance: 25.8,
    gameConfig: {
      kenoNumbers: [3, 14, 27, 38],
      kenoRisk: 'classic',
    },
    onWinAction: 'reset',
    onLossAction: 'increase_fixed',
    onLossValue: 0.02,
    stopOnProfit: 20.0,
    stopOnLoss: 20.0,
    maxBetLimit: 3.0,
    maxConsecutiveLosses: 15,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: 'Retours réguliers de 1.5x à 5x permettant de viser les gros gains sans perte de contrôle de la bankroll.'
  },
  {
    id: 'strat-keno-low-risk-grinder',
    name: 'Keno 3-Numéros Low Risk Grinder (x47 Max)',
    game: 'keno',
    description: 'Sélection de 3 numéros avec risque Faible / Low pour maximiser la fréquence des remboursements et des multiplicateurs réguliers.',
    riskLevel: 'low',
    baseBet: 0.25,
    currency: 'USDT',
    targetMultiplier: 2.7,
    winChance: 38.0,
    gameConfig: {
      kenoNumbers: [7, 18, 33],
      kenoRisk: 'low',
    },
    onWinAction: 'reset',
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 12.0,
    stopOnLoss: 15.0,
    maxBetLimit: 1.5,
    maxConsecutiveLosses: 10,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: 'Faible volatilité et gains fréquents, parfait pour une progression de solde sereine.'
  },
  {
    id: 'strat-keno-2numbers-scalp',
    name: 'Keno 2-Numéros Safe Scalp (x9.20 Low Risk)',
    game: 'keno',
    description: 'Sélection de 2 numéros seulement en risque Low (gain dès 1 numéro trouvé x1.10, jackpot à 2 numéros x9.20). Taux de succès élevé.',
    riskLevel: 'ultra_safe',
    baseBet: 0.40,
    currency: 'USDT',
    targetMultiplier: 1.80,
    winChance: 44.0,
    gameConfig: {
      kenoNumbers: [11, 29],
      kenoRisk: 'low',
    },
    onWinAction: 'reset',
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 10.0,
    stopOnLoss: 15.0,
    maxBetLimit: 2.0,
    maxConsecutiveLosses: 8,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: 'Près d’un tirage sur deux rapporte un gain ou un remboursement partiel, amortissant totalement la variance.'
  },
  {
    id: 'strat-keno-7numbers-high-yield',
    name: 'Keno 7-Numéros High Yield (x400 Max Classic)',
    game: 'keno',
    description: 'Sélection de 7 numéros bien répartis (paliers progressifs dès 3 hits jusqu’à x400 pour 7/7). Micro-mise étalée sur 100 tirages.',
    riskLevel: 'medium',
    baseBet: 0.10,
    currency: 'USDT',
    targetMultiplier: 7.0,
    winChance: 21.0,
    gameConfig: {
      kenoNumbers: [2, 9, 16, 23, 30, 35, 40],
      kenoRisk: 'classic',
    },
    onWinAction: 'reset',
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 25.0,
    stopOnLoss: 15.0,
    maxBetLimit: 0.50,
    maxConsecutiveLosses: 25,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: 'La combinaison de 7 numéros couvre 17.5% de la grille et capte de multiples paliers intermédiaires.'
  },
  {
    id: 'strat-keno-1number-fast-farm',
    name: 'Keno 1-Numéro Fast Farm (x3.80 Low Risk)',
    game: 'keno',
    description: 'Sélection d’un unique numéro fétiche (probabilité exacte de 25% qu’il sorte parmi les 10 boules tirées sur 40). Gain net de +2.8x.',
    riskLevel: 'low',
    baseBet: 0.30,
    currency: 'USDT',
    targetMultiplier: 3.80,
    winChance: 25.0,
    gameConfig: {
      kenoNumbers: [17],
      kenoRisk: 'low',
    },
    onWinAction: 'reset',
    onLossAction: 'increase_fixed',
    onLossValue: 0.05,
    stopOnProfit: 15.0,
    stopOnLoss: 15.0,
    maxBetLimit: 2.0,
    maxConsecutiveLosses: 12,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: '1 chance sur 4 exacte à chaque round : un succès rembourse 3.8 tirages avec gain net immédiat.'
  },
  {
    id: 'strat-keno-10numbers-moonshot',
    name: 'Keno 10-Numéros Moonshot (x1000 Max High Risk)',
    game: 'keno',
    description: 'Sélection complète de 10 numéros en mode High Risk pour viser les multiplicateurs extrêmes jusqu’à x1000. Micro-mise de 0.05 USDT.',
    riskLevel: 'high',
    baseBet: 0.05,
    currency: 'USDT',
    targetMultiplier: 50.0,
    winChance: 5.5,
    gameConfig: {
      kenoNumbers: [4, 8, 12, 16, 20, 24, 28, 32, 36, 40],
      kenoRisk: 'high',
    },
    onWinAction: 'reset',
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 30.0,
    stopOnLoss: 10.0,
    maxBetLimit: 0.20,
    maxConsecutiveLosses: 60,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: 'Structure asymétrique convexe : un seul tirage à 6+ bons numéros génère un gain disproportionné.'
  },

  // ==========================================
  // CRASH STRATEGIES
  // ==========================================
  {
    id: 'strat-crash-auto-cashout-2x',
    name: 'Crash Auto-Cashout 1.95x Discipliné',
    game: 'crash',
    description: 'Auto-cashout programmé à 1.95x (pour devancer le seuil psychologique de 2.0x). Mise plate avec objectif de cycle.',
    riskLevel: 'low',
    baseBet: 0.30,
    currency: 'USDT',
    targetMultiplier: 1.95,
    winChance: 50.70,
    gameConfig: {
      crashAutoCashout: 1.95,
    },
    onWinAction: 'reset',
    onLossAction: 'custom',
    onLossValue: 0,
    stopOnProfit: 10.0,
    stopOnLoss: 15.0,
    maxBetLimit: 2.0,
    maxConsecutiveLosses: 8,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: 'Retirer à 1.95x évite les crashs pièges à 1.99x et offre un taux de réussite régulier supérieur à 50%.'
  },
  {
    id: 'strat-crash-moonshot-safe',
    name: 'Crash Moonshot 10x à Micro-Mise',
    game: 'crash',
    description: 'Recherche de multiplicateurs x10.0 à très petite mise (0.1% de bankroll) avec réinitialisation à chaque round.',
    riskLevel: 'medium',
    baseBet: 0.10,
    currency: 'USDT',
    targetMultiplier: 10.0,
    winChance: 9.9,
    gameConfig: {
      crashAutoCashout: 10.0,
    },
    onWinAction: 'reset',
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 20.0,
    stopOnLoss: 10.0,
    maxBetLimit: 0.50,
    maxConsecutiveLosses: 30,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: 'Idéal pour capter les explosions sans rogner son capital grâce à une taille de mise infime.'
  },
  {
    id: 'strat-crash-kelly-scalper',
    name: 'Crash 1.25x Kelly Scalper (79.2% Win)',
    game: 'crash',
    description: 'Retrait automatique ultra-rapide programmé à 1.25x (79.20% de winrate). Dimensionnement Kelly fractionnaire pour une progression régulière.',
    riskLevel: 'ultra_safe',
    baseBet: 0.60,
    currency: 'USDT',
    targetMultiplier: 1.25,
    winChance: 79.20,
    gameConfig: {
      crashAutoCashout: 1.25,
    },
    onWinAction: 'reset',
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 10.0,
    stopOnLoss: 15.0,
    maxBetLimit: 2.5,
    maxConsecutiveLosses: 4,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: 'Quasiment 4 courses sur 5 atteignent 1.25x sans encombre, permettant de capitaliser calmement.'
  },
  {
    id: 'strat-crash-paroli-2stages',
    name: 'Crash Paroli 2-Paliers (1.80x Multiplier)',
    game: 'crash',
    description: 'Anti-Martingale sur 2 victoires consécutives à 1.80x. Mise de base constante sur défaite, doublement uniquement après un succès puis encaissement.',
    riskLevel: 'medium',
    baseBet: 0.25,
    currency: 'USDT',
    targetMultiplier: 1.80,
    winChance: 55.00,
    gameConfig: {
      crashAutoCashout: 1.80,
    },
    onWinAction: 'increase_pct',
    onWinValue: 80,
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 15.0,
    stopOnLoss: 15.0,
    maxBetLimit: 1.5,
    maxConsecutiveLosses: 7,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: 'Protège la bankroll lors des séries rouges et booste les gains sur les séries vertes avec seulement 2 paliers.'
  },
  {
    id: 'strat-crash-asymmetric-3x',
    name: 'Crash 3.0x Asymmetric Growth (33% Win)',
    game: 'crash',
    description: 'Auto-cashout programmé à 3.00x. Mise fixe modérée avec objectif de clore la session après 5 succès à 3x.',
    riskLevel: 'medium',
    baseBet: 0.20,
    currency: 'USDT',
    targetMultiplier: 3.00,
    winChance: 33.00,
    gameConfig: {
      crashAutoCashout: 3.00,
    },
    onWinAction: 'reset',
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 15.0,
    stopOnLoss: 12.0,
    maxBetLimit: 1.0,
    maxConsecutiveLosses: 15,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: 'Chaque victoire rapporte +2 unités nettes, ce qui compense immédiatement 2 défaites consécutives.'
  },
  {
    id: 'strat-crash-vip-safe-rail',
    name: 'Crash 1.10x VIP Safe Rail (90% Win)',
    game: 'crash',
    description: 'Auto-cashout ultra-bas à 1.10x conçu pour rouler du volume VIP et du rakeback avec un taux de réussite écrasant de 90%.',
    riskLevel: 'ultra_safe',
    baseBet: 1.00,
    currency: 'USDT',
    targetMultiplier: 1.10,
    winChance: 90.00,
    gameConfig: {
      crashAutoCashout: 1.10,
    },
    onWinAction: 'reset',
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 10.0,
    stopOnLoss: 20.0,
    maxBetLimit: 3.0,
    maxConsecutiveLosses: 3,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: 'Faible risque par round, idéal pour faire tourner le volume de jeu en toute sérénité.'
  },

  // ==========================================
  // HILO STRATEGIES
  // ==========================================
  {
    id: 'strat-hilo-stepdown-safe',
    name: 'Hilo Step-Down Probability Lock (x1.50)',
    game: 'hilo',
    description: 'Enchaînement de 2 décisions à haute probabilité (>70% par carte) puis encaissement systématique dès x1.50.',
    riskLevel: 'low',
    baseBet: 0.30,
    currency: 'USDT',
    targetMultiplier: 1.50,
    winChance: 65.0,
    gameConfig: {
      hiloStartCard: 7,
    },
    onWinAction: 'reset',
    onLossAction: 'increase_pct',
    onLossValue: 20,
    stopOnProfit: 10.0,
    stopOnLoss: 15.0,
    maxBetLimit: 2.0,
    maxConsecutiveLosses: 5,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: 'Évite la cupidité en sécurisant le bénéfice dès le palier x1.50 atteint avec deux cartes favorables.'
  },
  {
    id: 'strat-hilo-3cards-streak',
    name: 'Hilo 3-Cards Streak Lock (x2.20)',
    game: 'hilo',
    description: 'Enchaînement de 3 décisions logiques sur cartes extrêmes (cartes basses vers HIGH, cartes hautes vers LOW), encaissement garanti à x2.20.',
    riskLevel: 'low',
    baseBet: 0.25,
    currency: 'USDT',
    targetMultiplier: 2.20,
    winChance: 45.0,
    gameConfig: {
      hiloStartCard: 6,
    },
    onWinAction: 'reset',
    onLossAction: 'increase_fixed',
    onLossValue: 0.05,
    stopOnProfit: 15.0,
    stopOnLoss: 15.0,
    maxBetLimit: 2.0,
    maxConsecutiveLosses: 8,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: 'Sauter (Skip) les cartes médianes neutres (7 et 8) permet d’optimiser l’espérance mathématique des 3 tirages.'
  },
  {
    id: 'strat-hilo-extremes-scalp',
    name: 'Hilo Conservative Extremes (x1.30)',
    game: 'hilo',
    description: 'Jeu strict uniquement sur les cartes d’extrémités (As, 2, Roi, Dame) avec retrait instantané après 1 seule carte devinée à >85% de certitude.',
    riskLevel: 'ultra_safe',
    baseBet: 0.60,
    currency: 'USDT',
    targetMultiplier: 1.30,
    winChance: 82.0,
    gameConfig: {
      hiloStartCard: 2,
    },
    onWinAction: 'reset',
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 10.0,
    stopOnLoss: 15.0,
    maxBetLimit: 2.0,
    maxConsecutiveLosses: 4,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: 'Les cartes extrêmes offrent une quasi-certitude statistique : 1 seul clic puis cashout sécurisé.'
  },
  {
    id: 'strat-hilo-escalator-5step',
    name: 'Hilo 5-Step Escalator Asymétrique (x4.50)',
    game: 'hilo',
    description: 'Progression contrôlée sur 5 cartes favorables à micro-mise fixe (0.1 USDT). Encaissement dès le palier 4.5x atteint.',
    riskLevel: 'medium',
    baseBet: 0.10,
    currency: 'USDT',
    targetMultiplier: 4.50,
    winChance: 22.0,
    gameConfig: {
      hiloStartCard: 3,
    },
    onWinAction: 'reset',
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 20.0,
    stopOnLoss: 12.0,
    maxBetLimit: 0.50,
    maxConsecutiveLosses: 20,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: 'Micro-mise pour viser un gain net de +3.5 unités sur chaque série de 5 cartes réussie.'
  },
  {
    id: 'strat-hilo-dalembert',
    name: "Hilo D'Alembert Linéaire (x1.75)",
    game: 'hilo',
    description: 'Progression linéaire douce : +0.05 USDT après une manche perdue, -0.05 USDT après un gain. Encaissement dès 2 cartes réussies.',
    riskLevel: 'low',
    baseBet: 0.30,
    currency: 'USDT',
    targetMultiplier: 1.75,
    winChance: 56.5,
    gameConfig: {
      hiloStartCard: 8,
    },
    onWinAction: 'custom',
    onLossAction: 'increase_fixed',
    onLossValue: 0.05,
    stopOnProfit: 12.0,
    stopOnLoss: 15.0,
    maxBetLimit: 2.0,
    maxConsecutiveLosses: 7,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: 'La progression linéaire protège le solde et permet de ressortir gagnant même avec une variance moyenne.'
  },

  // ==========================================
  // WHEEL STRATEGIES
  // ==========================================
  {
    id: 'strat-wheel-10seg-low-risk',
    name: 'Wheel 10 Segments Low Risk (x1.50 - 60% Win)',
    game: 'wheel',
    description: 'Roue Stake 10 segments en risque Low (6 segments gagnants sur 10 à 1.50x). Mise plate avec objectif de cycle régulier.',
    riskLevel: 'ultra_safe',
    baseBet: 0.40,
    currency: 'USDT',
    targetMultiplier: 1.50,
    winChance: 60.0,
    gameConfig: {
      wheelSegments: 10,
      wheelRisk: 'low',
    },
    onWinAction: 'reset',
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 10.0,
    stopOnLoss: 15.0,
    maxBetLimit: 2.0,
    maxConsecutiveLosses: 5,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: 'Taux de gain de 60% sur les segments majoritaires, idéal pour une progression sans heurt.'
  },
  {
    id: 'strat-wheel-20seg-medium',
    name: 'Wheel 20 Segments Medium Balance (x3.00)',
    game: 'wheel',
    description: 'Roue 20 segments en risque Moyen. Cible les segments 3.0x et 5.0x avec gestion linéaire douce sans doublement destructeur.',
    riskLevel: 'low',
    baseBet: 0.25,
    currency: 'USDT',
    targetMultiplier: 3.00,
    winChance: 33.0,
    gameConfig: {
      wheelSegments: 20,
      wheelRisk: 'medium',
    },
    onWinAction: 'reset',
    onLossAction: 'increase_fixed',
    onLossValue: 0.05,
    stopOnProfit: 15.0,
    stopOnLoss: 15.0,
    maxBetLimit: 1.5,
    maxConsecutiveLosses: 10,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: 'Le multiplicateur 3.0x offre une belle respiration de bankroll et amortit les tours blancs.'
  },
  {
    id: 'strat-wheel-50seg-high-hunter',
    name: 'Wheel 50 Segments High Risk Hunter (x49.50)',
    game: 'wheel',
    description: 'Roue 50 segments High Risk : micro-mises fixes (0.05 USDT) pour capter le jackpot x49.50. Aucune hausse sur perte.',
    riskLevel: 'high',
    baseBet: 0.05,
    currency: 'USDT',
    targetMultiplier: 49.50,
    winChance: 2.0,
    gameConfig: {
      wheelSegments: 50,
      wheelRisk: 'high',
    },
    onWinAction: 'reset',
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 25.0,
    stopOnLoss: 10.0,
    maxBetLimit: 0.20,
    maxConsecutiveLosses: 80,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: 'Asymétrie positive pure : un seul segment x49.50 compense 50 tours et dégage un bénéfice net immédiat.'
  },
  {
    id: 'strat-wheel-oscars-grind',
    name: "Wheel Oscar's Grind (x2.00)",
    game: 'wheel',
    description: 'Objectif de +1 unité par cycle sur les segments à 2.0x de la Roue. Mise constante sur chaque échec, hausse uniquement après victoire.',
    riskLevel: 'low',
    baseBet: 0.30,
    currency: 'USDT',
    targetMultiplier: 2.00,
    winChance: 49.5,
    gameConfig: {
      wheelSegments: 30,
      wheelRisk: 'medium',
    },
    onWinAction: 'increase_fixed',
    onWinValue: 0.30,
    onLossAction: 'custom',
    onLossValue: 0,
    stopOnProfit: 12.0,
    stopOnLoss: 18.0,
    maxBetLimit: 2.0,
    maxConsecutiveLosses: 8,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: 'Permet de naviguer la roue Stake sereinement sans jamais voir sa mise exploser.'
  },
  {
    id: 'strat-wheel-dual-sector',
    name: 'Wheel Dual-Sector Balance (x2.00)',
    game: 'wheel',
    description: 'Mise plate constante sur les segments médians avec un ratio de couverture équilibré pour stabiliser la balance.',
    riskLevel: 'low',
    baseBet: 0.35,
    currency: 'USDT',
    targetMultiplier: 2.00,
    winChance: 49.5,
    gameConfig: {
      wheelSegments: 20,
      wheelRisk: 'low',
    },
    onWinAction: 'reset',
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 10.0,
    stopOnLoss: 15.0,
    maxBetLimit: 1.5,
    maxConsecutiveLosses: 6,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: 'Variance minimale, idéal pour des sessions détendues et le déblocage régulier de milestones.'
  },

  // ==========================================
  // BLACKJACK STRATEGIES
  // ==========================================
  {
    id: 'strat-blackjack-basic-perfect',
    name: 'Blackjack Basic Strategy Mathématiquement Parfaite',
    game: 'blackjack',
    description: 'Application stricte du tableau de base mathématique (Dealer stands on Soft 17, RTP 99.43%). Mise plate constante avec stop-loss / take-profit.',
    riskLevel: 'low',
    baseBet: 0.50,
    currency: 'USDT',
    targetMultiplier: 2.0,
    winChance: 49.20,
    gameConfig: {
      blackjackRule: 'dealer_stands_soft_17',
    },
    onWinAction: 'reset',
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 10.0,
    stopOnLoss: 20.0,
    maxBetLimit: 2.0,
    maxConsecutiveLosses: 8,
    evEstimate: -0.0057,
    author: 'system',
    aiRationale: 'Le Blackjack joué à la perfection offre le meilleur RTP de tout le casino (99.43%), réduisant l’avantage de la maison à seulement 0.57%.'
  },
  {
    id: 'strat-blackjack-flat-conservative',
    name: 'Blackjack Flat Betting Conservateur (1% Bankroll)',
    game: 'blackjack',
    description: 'Mise plate calibrée à 1.0% de votre bankroll totale. Respect absolu des règles de base (Split As & 8, Doubler 10/11, Ne jamais prendre assurance).',
    riskLevel: 'ultra_safe',
    baseBet: 0.50,
    currency: 'USDT',
    targetMultiplier: 2.0,
    winChance: 49.20,
    gameConfig: {
      blackjackRule: 'flat_1pct',
    },
    onWinAction: 'reset',
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 8.0,
    stopOnLoss: 15.0,
    maxBetLimit: 1.5,
    maxConsecutiveLosses: 7,
    evEstimate: -0.0057,
    author: 'system',
    aiRationale: 'Élimine tout risque d’emballement psychologique et maximise la longévité de session.'
  },
  {
    id: 'strat-blackjack-fractional-kelly',
    name: 'Blackjack Fractional Kelly (2% Bankroll)',
    game: 'blackjack',
    description: 'Mise calibrée selon le critère de Kelly fractionnaire avec ajustement automatique après chaque main et stop-loss strict à -20%.',
    riskLevel: 'low',
    baseBet: 0.80,
    currency: 'USDT',
    targetMultiplier: 2.0,
    winChance: 49.20,
    gameConfig: {
      blackjackRule: 'kelly_fractional',
    },
    onWinAction: 'reset',
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 15.0,
    stopOnLoss: 20.0,
    maxBetLimit: 3.0,
    maxConsecutiveLosses: 6,
    evEstimate: -0.0057,
    author: 'system',
    aiRationale: 'Optimise la croissance de capital sur le long terme tout en maintenant une barrière anti-ruine impénétrable.'
  },
  {
    id: 'strat-blackjack-positive-escalation',
    name: 'Blackjack 1-2 Units Positive Escalation',
    game: 'blackjack',
    description: 'Mise de 1 unité de base. En cas de victoire, montée à 2 unités pour la main suivante. En cas de perte, retour immédiat à 1 unité.',
    riskLevel: 'medium',
    baseBet: 0.40,
    currency: 'USDT',
    targetMultiplier: 2.0,
    winChance: 49.20,
    gameConfig: {
      blackjackRule: 'positive_1_2',
    },
    onWinAction: 'increase_pct',
    onWinValue: 100,
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 12.0,
    stopOnLoss: 16.0,
    maxBetLimit: 2.0,
    maxConsecutiveLosses: 7,
    evEstimate: -0.0057,
    author: 'system',
    aiRationale: 'Permet de tirer parti des séries de cartes favorables sans jamais doubler sur les défaites.'
  },
  {
    id: 'strat-blackjack-flash-target',
    name: 'Blackjack Flash Session +5 Unités (Take Profit)',
    game: 'blackjack',
    description: 'Session courte de 15 mains max avec objectif strict de +5 unités de profit net, puis encaissement garanti et arrêt.',
    riskLevel: 'low',
    baseBet: 0.50,
    currency: 'USDT',
    targetMultiplier: 2.0,
    winChance: 49.20,
    gameConfig: {
      blackjackRule: 'flash_session',
    },
    onWinAction: 'reset',
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 5.0,
    stopOnLoss: 10.0,
    maxBetLimit: 1.5,
    maxConsecutiveLosses: 5,
    evEstimate: -0.0057,
    author: 'system',
    aiRationale: 'Réduit le temps d’exposition à l’avantage de la maison : entrer, gagner 5 unités, sortir.'
  },

  // ==========================================
  // ROULETTE STRATEGIES
  // ==========================================
  {
    id: 'strat-roulette-sectors-coverage',
    name: 'Roulette Voisins du Zéro (45.9% Couverture)',
    game: 'roulette',
    description: 'Couverture stratégique de 17 numéros entourant le zéro (9 jetons). Excellente couverture du cylindre avec variance amortie.',
    riskLevel: 'low',
    baseBet: 0.90,
    currency: 'USDT',
    targetMultiplier: 2.18,
    winChance: 45.90,
    gameConfig: {
      rouletteSector: 'voisins',
    },
    onWinAction: 'reset',
    onLossAction: 'custom',
    onLossValue: 0,
    stopOnProfit: 15.0,
    stopOnLoss: 25.0,
    maxBetLimit: 4.50,
    maxConsecutiveLosses: 7,
    evEstimate: -0.027,
    author: 'system',
    aiRationale: 'La couverture de secteur physique offre une régularité bien supérieure aux paris pleins isolés.'
  },
  {
    id: 'strat-roulette-double-dozen',
    name: 'Roulette Double Douzaines (64.8% Couverture)',
    game: 'roulette',
    description: 'Pari sur 2 douzaines simultanées (24 numéros sur 37). Gain de +0.5x unité par tour gagnant avec 64.8% de chances de succès.',
    riskLevel: 'low',
    baseBet: 1.00,
    currency: 'USDT',
    targetMultiplier: 1.50,
    winChance: 64.86,
    gameConfig: {
      rouletteDozens: [1, 2],
    },
    onWinAction: 'reset',
    onLossAction: 'increase_fixed',
    onLossValue: 0.50,
    stopOnProfit: 12.0,
    stopOnLoss: 20.0,
    maxBetLimit: 5.0,
    maxConsecutiveLosses: 5,
    evEstimate: -0.027,
    author: 'system',
    aiRationale: 'Taux de réussite élevé (presque 2 coups sur 3), idéal pour consolider un bilan sans grosse prise de risque.'
  },
  {
    id: 'strat-roulette-tiers-du-cylindre',
    name: 'Roulette Tiers du Cylindre (32.4% Couverture - 6 Jetons)',
    game: 'roulette',
    description: 'Couvre 12 numéros opposés au zéro avec 6 chevalets (5/8, 10/11, 13/16, 23/24, 27/30, 33/36). Gain net de +12 jetons par tirage gagnant.',
    riskLevel: 'low',
    baseBet: 0.60,
    currency: 'USDT',
    targetMultiplier: 3.00,
    winChance: 32.43,
    gameConfig: {
      rouletteSector: 'tiers',
    },
    onWinAction: 'reset',
    onLossAction: 'increase_fixed',
    onLossValue: 0.06,
    stopOnProfit: 15.0,
    stopOnLoss: 20.0,
    maxBetLimit: 3.0,
    maxConsecutiveLosses: 8,
    evEstimate: -0.027,
    author: 'system',
    aiRationale: 'Le tiers du cylindre permet de capter un retour de 3 contre 1 net tout en couvrant un tiers complet de la roue physique.'
  },
  {
    id: 'strat-roulette-orphelins',
    name: 'Roulette Orphelins à Cheval (21.6% Couverture - 5 Jetons)',
    game: 'roulette',
    description: 'Couvre les 8 numéros orphelins avec 5 jetons (1 plein sur 1, et 4 chevalets 6/9, 14/17, 17/20, 31/34). Gain net jusqu’à +31 jetons.',
    riskLevel: 'medium',
    baseBet: 0.50,
    currency: 'USDT',
    targetMultiplier: 3.60,
    winChance: 21.62,
    gameConfig: {
      rouletteSector: 'orphelins',
    },
    onWinAction: 'reset',
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 20.0,
    stopOnLoss: 15.0,
    maxBetLimit: 2.0,
    maxConsecutiveLosses: 12,
    evEstimate: -0.027,
    author: 'system',
    aiRationale: 'Stratégie asymétrique classique des casinos européens : coût réduit (5 jetons) pour des gains substantiels à chaque sortie.'
  },
  {
    id: 'strat-roulette-jeu-zero',
    name: 'Roulette Jeu Zéro (18.9% Couverture - 4 Jetons)',
    game: 'roulette',
    description: 'Mini-secteur ultra-concentré de 7 numéros autour de la case 0 (1 plein sur le 26 et 3 chevalets). Gain net de +14 à +32 jetons.',
    riskLevel: 'medium',
    baseBet: 0.40,
    currency: 'USDT',
    targetMultiplier: 4.50,
    winChance: 18.92,
    gameConfig: {
      rouletteSector: 'zero',
    },
    onWinAction: 'reset',
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 18.0,
    stopOnLoss: 15.0,
    maxBetLimit: 2.0,
    maxConsecutiveLosses: 15,
    evEstimate: -0.027,
    author: 'system',
    aiRationale: 'Idéal lorsque le croupier ou l’algorithme a tendance à répéter les sorties autour du zéro.'
  },
  {
    id: 'strat-roulette-columns-dalembert',
    name: "Roulette 2 Colonnes D'Alembert Doux (64.8% Couverture)",
    game: 'roulette',
    description: "Pari simultané sur 2 colonnes avec ajustement arithmétique linéaire (+0.10 USDT après défaite, -0.10 USDT après victoire). Gain net fluide.",
    riskLevel: 'low',
    baseBet: 0.80,
    currency: 'USDT',
    targetMultiplier: 1.50,
    winChance: 64.86,
    gameConfig: {
      rouletteDozens: [1, 3],
    },
    onWinAction: 'custom',
    onLossAction: 'increase_fixed',
    onLossValue: 0.10,
    stopOnProfit: 12.0,
    stopOnLoss: 20.0,
    maxBetLimit: 4.0,
    maxConsecutiveLosses: 6,
    evEstimate: -0.027,
    author: 'system',
    aiRationale: 'Avec presque 2 chances sur 3 de succès, la progression douce D’Alembert compense les séries creuses sans risque de surchauffe.'
  },

  // ==========================================
  // WAGER & HIGH-VOLUME VIP OPTIMIZED STRATEGIES
  // ==========================================
  {
    id: 'strat-wager-dice-98',
    name: '⚡ [WAGER] Dice 98.00% Ultra-Volume VIP Farmer (1.0102x)',
    game: 'dice',
    description: 'Le standard absolu du Wagering Stake : probabilité de gain de 98.00% (cote 1.0102x). Mises plates calibrées à 0.8% de la bankroll pour générer un volume massif (>350x le capital) avec variance minimale.',
    riskLevel: 'ultra_safe',
    baseBet: 0.80,
    currency: 'USDT',
    targetMultiplier: 1.0102,
    winChance: 98.00,
    isWagerStrategy: true,
    wagerTargetVolume: 35000,
    estimatedWagerTurnover: 380,
    estimatedRakebackPercent: 10,
    vipTierTarget: 'Platine / Diamant',
    gameConfig: {
      diceCondition: 'above',
      diceTarget: 1.99,
    },
    onWinAction: 'reset',
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 10.0,
    stopOnLoss: 20.0,
    maxBetLimit: 3.20,
    maxConsecutiveLosses: 2,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: 'Grâce au RTP de 99% et un winrate de 98%, chaque cycle produit un volume de roulement colossal pour débloquer les paliers VIP Stake (Bronze -> Platine) et maximiser le rakeback sans risque de crash.'
  },
  {
    id: 'strat-wager-dice-95',
    name: '⚡ [WAGER] Dice 95.00% Balanced Turnover VIP (1.0421x)',
    game: 'dice',
    description: 'Volume VIP équilibré à 95.00% de winrate. Permet de générer ~250x le capital en volume de mise tout en encaissant régulièrement de petits profits.',
    riskLevel: 'ultra_safe',
    baseBet: 0.60,
    currency: 'USDT',
    targetMultiplier: 1.0421,
    winChance: 95.00,
    isWagerStrategy: true,
    wagerTargetVolume: 25000,
    estimatedWagerTurnover: 270,
    estimatedRakebackPercent: 10,
    vipTierTarget: 'Gold / Platine',
    gameConfig: {
      diceCondition: 'above',
      diceTarget: 4.99,
    },
    onWinAction: 'reset',
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 12.0,
    stopOnLoss: 20.0,
    maxBetLimit: 2.40,
    maxConsecutiveLosses: 3,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: "Cote 1.042x réduisant l'érosion tout en maintenant une vitesse d'exécution de 10 à 30 paris par seconde."
  },
  {
    id: 'strat-wager-limbo-102',
    name: '⚡ [WAGER] Limbo 1.02x Instant Micro-Cashout (97.06% Win)',
    game: 'limbo',
    description: 'Auto-retrait immédiat à 1.02x sur Limbo. Rotation ultra-rapide et mise plate constante pour empiler du volume de mise certifié Provably Fair.',
    riskLevel: 'ultra_safe',
    baseBet: 0.70,
    currency: 'USDT',
    targetMultiplier: 1.02,
    winChance: 97.06,
    isWagerStrategy: true,
    wagerTargetVolume: 30000,
    estimatedWagerTurnover: 320,
    estimatedRakebackPercent: 10,
    vipTierTarget: 'Platine',
    gameConfig: {
      limboTarget: 1.02,
    },
    onWinAction: 'reset',
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 10.0,
    stopOnLoss: 20.0,
    maxBetLimit: 2.80,
    maxConsecutiveLosses: 2,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: 'Limbo offre la vitesse de roll la plus élevée de Stake. À 1.02x, 97 paris sur 100 sont gagnants.'
  },
  {
    id: 'strat-wager-mines-96',
    name: '⚡ [WAGER] Mines 1-Mine 1-Gem 96% Probabilité (1.03x)',
    game: 'mines',
    description: '1 seule mine sur la grille 5x5, encaissement dès la 1ère gemme découverte (24 chances sur 25 soit 96% de réussite). Mise plate et auto-cashout instantané.',
    riskLevel: 'ultra_safe',
    baseBet: 0.80,
    currency: 'USDT',
    targetMultiplier: 1.03,
    winChance: 96.00,
    isWagerStrategy: true,
    wagerTargetVolume: 28000,
    estimatedWagerTurnover: 290,
    estimatedRakebackPercent: 10,
    vipTierTarget: 'Platine',
    gameConfig: {
      minesCount: 1,
      minesGemsToCashout: 1,
      minesChosenTiles: [0],
    },
    onWinAction: 'reset',
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 10.0,
    stopOnLoss: 20.0,
    maxBetLimit: 3.20,
    maxConsecutiveLosses: 2,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: 'Permet de générer des milliers de paris sans stress avec un taux de réussite quasi continu.'
  },
  {
    id: 'strat-wager-plinko-8low',
    name: '⚡ [WAGER] Plinko 8 Rows Low Risk Max Flips (99% RTP Cushion)',
    game: 'plinko',
    description: 'Plinko 8 rangées en risque Low : aucun trou à 0x ! Le multiplicateur minimum est de 0.5x, ce qui amortit immédiatement toute perte et permet un turnover de volume exceptionnel.',
    riskLevel: 'ultra_safe',
    baseBet: 0.60,
    currency: 'USDT',
    targetMultiplier: 1.10,
    winChance: 85.00,
    isWagerStrategy: true,
    wagerTargetVolume: 40000,
    estimatedWagerTurnover: 420,
    estimatedRakebackPercent: 10,
    vipTierTarget: 'Diamant',
    gameConfig: {
      plinkoRows: 8,
      plinkoRisk: 'low',
    },
    onWinAction: 'reset',
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 15.0,
    stopOnLoss: 20.0,
    maxBetLimit: 2.40,
    maxConsecutiveLosses: 5,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: 'Le coussin de sécurité des billes (0.5x minimum) permet de faire tourner 400x à 600x la bankroll sans crash de capital.'
  },
  {
    id: 'strat-wager-crash-105',
    name: '⚡ [WAGER] Crash 1.05x Safe Autobet Extractor (94.3% Win)',
    game: 'crash',
    description: 'Auto-cashout programmé à 1.05x sur Crash. Sortie quasi-instantanée dès le décollage de la fusée avec mise unitaire constante.',
    riskLevel: 'ultra_safe',
    baseBet: 0.50,
    currency: 'USDT',
    targetMultiplier: 1.05,
    winChance: 94.28,
    isWagerStrategy: true,
    wagerTargetVolume: 22000,
    estimatedWagerTurnover: 230,
    estimatedRakebackPercent: 10,
    vipTierTarget: 'Silver / Gold',
    gameConfig: {
      crashAutoCashout: 1.05,
    },
    onWinAction: 'reset',
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 10.0,
    stopOnLoss: 20.0,
    maxBetLimit: 2.0,
    maxConsecutiveLosses: 3,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: 'Évite les crashs soudains au-dessus de 1.10x et capitalise sur la forte proportion de courses réussies.'
  },
  {
    id: 'strat-wager-roulette-dozens',
    name: '⚡ [WAGER] Roulette 2-Dozens 64.8% Coverage (1.50x)',
    game: 'roulette',
    description: 'Couverture simultanée de 2 douzaines sur 3 (24 numéros sur 37 soit 64.8% de chances). Multiplicateur net de 1.50x avec mise constante.',
    riskLevel: 'low',
    baseBet: 0.50,
    currency: 'USDT',
    targetMultiplier: 1.50,
    winChance: 64.86,
    isWagerStrategy: true,
    wagerTargetVolume: 18000,
    estimatedWagerTurnover: 190,
    estimatedRakebackPercent: 10,
    vipTierTarget: 'Silver',
    gameConfig: {
      rouletteSector: 'dozens',
      rouletteDozens: [1, 2],
    },
    onWinAction: 'reset',
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 12.0,
    stopOnLoss: 22.0,
    maxBetLimit: 2.0,
    maxConsecutiveLosses: 4,
    evEstimate: -0.027,
    author: 'system',
    aiRationale: 'La couverture des deux tiers du cylindre européenne stabilise la courbe de gains et génère un roulement continu.'
  },
  {
    id: 'strat-wager-wheel-10low',
    name: '⚡ [WAGER] Wheel 10 Segments Low Risk Grinder (1.50x)',
    game: 'wheel',
    description: 'Roue 10 segments Low Risk (60% de segments payants à 1.50x). Mise plate et rotation rapide sans hausse exponentielle.',
    riskLevel: 'ultra_safe',
    baseBet: 0.50,
    currency: 'USDT',
    targetMultiplier: 1.50,
    winChance: 60.00,
    isWagerStrategy: true,
    wagerTargetVolume: 15000,
    estimatedWagerTurnover: 160,
    estimatedRakebackPercent: 10,
    vipTierTarget: 'Bronze / Silver',
    gameConfig: {
      wheelSegments: 10,
      wheelRisk: 'low',
    },
    onWinAction: 'reset',
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 12.0,
    stopOnLoss: 20.0,
    maxBetLimit: 2.0,
    maxConsecutiveLosses: 5,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: 'Taux de hit supérieur à 1 chance sur 2 pour accumuler du wager sans heurt.'
  },
  {
    id: 'strat-wager-blackjack-basic',
    name: '⚡ [WAGER] Blackjack 99.43% RTP Flat Bet (Basic Strategy)',
    game: 'blackjack',
    description: 'Le jeu au meilleur RTP du casino (99.43%). Mises plates rigoureuses suivant à 100% le tableau mathématique de base pour générer un volume maximal avec un avantage maison de seulement 0.57%.',
    riskLevel: 'ultra_safe',
    baseBet: 0.40,
    currency: 'USDT',
    targetMultiplier: 2.00,
    winChance: 49.20,
    isWagerStrategy: true,
    wagerTargetVolume: 45000,
    estimatedWagerTurnover: 450,
    estimatedRakebackPercent: 10,
    vipTierTarget: 'Diamant / VIP Élite',
    gameConfig: {
      blackjackRule: 'standard',
    },
    onWinAction: 'reset',
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 15.0,
    stopOnLoss: 20.0,
    maxBetLimit: 1.60,
    maxConsecutiveLosses: 8,
    evEstimate: -0.0057,
    author: 'system',
    aiRationale: "Avec 99.43% de retour théorique, le Blackjack est idéal pour faire tourner des dizaines de milliers de dollars de volume tout en limitant les pertes à l'épaisseur du trait."
  },

  // ==========================================
  // WAGER RECOVERY & STOP-LOSS RECOUP STRATEGIES
  // ==========================================
  {
    id: 'strat-wager-rec-dice-dalembert',
    name: "🛡️ [WAGER RECOVERY] Dice 95% D'Alembert Récupérateur Linéaire (1.042x)",
    game: 'dice',
    description: "Stratégie de récupération post-Stop Loss ou drawdown Wager : cote ultra-sûre 1.042x (95.0% Win). Progression arithmétique douce (+0.05 USDT sur perte, -0.05 USDT sur gain). Recouvre le déficit du stop-loss en douceur sans aucune hausse exponentielle.",
    riskLevel: 'ultra_safe',
    baseBet: 0.30,
    currency: 'USDT',
    targetMultiplier: 1.0421,
    winChance: 95.00,
    isWagerStrategy: true,
    isRecoveryStrategy: true,
    recoveryTargetType: 'stop_loss_recoup',
    recoveryPhaseNotes: 'Reconstitue 100% du drawdown de stop-loss par micro-paliers réguliers.',
    wagerTargetVolume: 15000,
    estimatedWagerTurnover: 150,
    vipTierTarget: 'Gold / Platine',
    gameConfig: {
      diceCondition: 'above',
      diceTarget: 4.99,
    },
    onWinAction: 'custom',
    onLossAction: 'increase_fixed',
    onLossValue: 0.05,
    stopOnProfit: 15.0,
    stopOnLoss: 12.0,
    maxBetLimit: 1.50,
    maxConsecutiveLosses: 3,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: "En cas d'atteinte du stop-loss sur une stratégie Wager classique, cette méthode amortit la variance et remonte la bankroll pas à pas grâce au taux de victoire de 95%."
  },
  {
    id: 'strat-wager-rec-dice-oscars-grind',
    name: "🛡️ [WAGER RECOVERY] Oscar's Grind Lissé 2.0x Post-Stop Loss",
    game: 'dice',
    description: "Récupérateur par cycles stricts de +1 unité (+0.20 USDT). La mise reste FIXE sur chaque perte (zéro martingale) et n'augmente que lors des victoires pour clore le cycle à profit net, puis réinitialisation immédiate.",
    riskLevel: 'low',
    baseBet: 0.20,
    currency: 'USDT',
    targetMultiplier: 2.0,
    winChance: 49.50,
    isWagerStrategy: true,
    isRecoveryStrategy: true,
    recoveryTargetType: 'stop_loss_recoup',
    recoveryPhaseNotes: 'Cycle d\'Oscar\'s Grind visant 5 à 10 cycles complets pour combler le déficit de perte.',
    wagerTargetVolume: 12000,
    estimatedWagerTurnover: 120,
    vipTierTarget: 'Silver / Gold',
    gameConfig: {
      diceCondition: 'above',
      diceTarget: 50.49,
    },
    onWinAction: 'increase_fixed',
    onWinValue: 0.20,
    onLossAction: 'custom',
    onLossValue: 0,
    stopOnProfit: 10.0,
    stopOnLoss: 15.0,
    maxBetLimit: 1.80,
    maxConsecutiveLosses: 8,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: "La méthode d'Oscar's Grind est l'anti-martingale par excellence pour redresser une courbe de bankroll après une séquence rouge."
  },
  {
    id: 'strat-wager-rec-limbo-kelly',
    name: "🛡️ [WAGER RECOVERY] Limbo 1.35x Fractional Kelly Rebuilder (73.3% Win)",
    game: 'limbo',
    description: "Reconstitution active du capital par le critère de Kelly fractionnaire (25% Kelly). Cote cible de 1.35x (73.3% win chance) avec mise unitaire constante et take-profit calibré au montant exact du stop loss subi.",
    riskLevel: 'low',
    baseBet: 0.40,
    currency: 'USDT',
    targetMultiplier: 1.35,
    winChance: 73.33,
    isWagerStrategy: true,
    isRecoveryStrategy: true,
    recoveryTargetType: 'wager_drawdown',
    recoveryPhaseNotes: 'Optimise la croissance logarithmique sans risque de ruine après drawdown.',
    wagerTargetVolume: 18000,
    estimatedWagerTurnover: 180,
    vipTierTarget: 'Gold',
    gameConfig: {
      limboTarget: 1.35,
    },
    onWinAction: 'reset',
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 15.0,
    stopOnLoss: 15.0,
    maxBetLimit: 1.60,
    maxConsecutiveLosses: 4,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: "Presque 3 paris sur 4 gagnants à 1.35x. Permet de compenser les pertes de wagering tout en maintenant un volume de turnover sain."
  },
  {
    id: 'strat-wager-rec-mines-safe',
    name: "🛡️ [WAGER RECOVERY] Mines 1-Mine 2-Gems Sécurité Micro-Paliers (1.07x)",
    game: 'mines',
    description: "Grille 5x5 avec 1 seule mine. Révélation de 2 gemmes sécurisées (92.0% probabilité cumulée) pour un gain net de +7.5% par tour. Encaissement automatique instantané pour neutraliser le drawdown.",
    riskLevel: 'ultra_safe',
    baseBet: 0.50,
    currency: 'USDT',
    targetMultiplier: 1.075,
    winChance: 92.00,
    isWagerStrategy: true,
    isRecoveryStrategy: true,
    recoveryTargetType: 'stop_loss_recoup',
    recoveryPhaseNotes: '2 gemmes fixes à chaque tour, cashout automatique immédiat.',
    wagerTargetVolume: 20000,
    estimatedWagerTurnover: 200,
    vipTierTarget: 'Platine',
    gameConfig: {
      minesCount: 1,
      minesGemsToCashout: 2,
      minesChosenTiles: [0, 1],
    },
    onWinAction: 'reset',
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 12.0,
    stopOnLoss: 15.0,
    maxBetLimit: 2.00,
    maxConsecutiveLosses: 2,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: "Le compromis idéal entre sécurité (92% winrate) et rendement (1.075x) pour remonter 10 à 20 USDT de perte en quelques dizaines de tours stables."
  },
  {
    id: 'strat-wager-rec-plinko-cushion',
    name: "🛡️ [WAGER RECOVERY] Plinko 10-Rows Low-Risk Cushion Rebuilder (99% RTP)",
    game: 'plinko',
    description: "Plinko 10 rangées en risque Low. Le multiplicateur minimum de 0.5x amortit chaque balle au lieu d'une perte totale (0x). Taux de restitution continu pour stabiliser la balance après un accident de parcours.",
    riskLevel: 'ultra_safe',
    baseBet: 0.40,
    currency: 'USDT',
    targetMultiplier: 1.20,
    winChance: 82.00,
    isWagerStrategy: true,
    isRecoveryStrategy: true,
    recoveryTargetType: 'wager_drawdown',
    recoveryPhaseNotes: 'Amortisseur de billes à 0.5x minimum sur 10 rangées.',
    wagerTargetVolume: 25000,
    estimatedWagerTurnover: 250,
    vipTierTarget: 'Platine',
    gameConfig: {
      plinkoRows: 10,
      plinkoRisk: 'low',
    },
    onWinAction: 'reset',
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 12.0,
    stopOnLoss: 16.0,
    maxBetLimit: 1.60,
    maxConsecutiveLosses: 4,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: "Aucun zéro sur la grille Low : la bankroll ne subit jamais de choc violent, ce qui permet un redressement en douceur."
  },
  {
    id: 'strat-wager-rec-crash-stepper',
    name: "🛡️ [WAGER RECOVERY] Crash 1.15x Safe Stepper Déblocage Drawdown (86% Win)",
    game: 'crash',
    description: "Retrait automatique anticipé à 1.15x sur Crash (86.08% de réussite). Mises plates sans escalade pour sécuriser +15% de profit par tirage validé.",
    riskLevel: 'ultra_safe',
    baseBet: 0.40,
    currency: 'USDT',
    targetMultiplier: 1.15,
    winChance: 86.08,
    isWagerStrategy: true,
    isRecoveryStrategy: true,
    recoveryTargetType: 'stop_loss_recoup',
    recoveryPhaseNotes: 'Cashout systématique dès 1.15x pour éviter les crashs tardifs.',
    wagerTargetVolume: 16000,
    estimatedWagerTurnover: 160,
    vipTierTarget: 'Gold',
    gameConfig: {
      crashAutoCashout: 1.15,
    },
    onWinAction: 'reset',
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 10.0,
    stopOnLoss: 14.0,
    maxBetLimit: 1.60,
    maxConsecutiveLosses: 3,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: "Idéal pour sortir d'une phase de perte sans prendre de risque excessif sur les multiplicateurs élevés."
  },
  {
    id: 'strat-wager-rec-roulette-dozens',
    name: "🛡️ [WAGER RECOVERY] Roulette Double Douzaines Récupération Linéaire (64.8%)",
    game: 'roulette',
    description: "Couverture de 2 douzaines (24 numéros sur 37). Gain de +0.5 unité par succès avec progression douce D'Alembert (+0.10u sur défaite, -0.10u sur victoire) pour effacer le déficit.",
    riskLevel: 'low',
    baseBet: 0.60,
    currency: 'USDT',
    targetMultiplier: 1.50,
    winChance: 64.86,
    isWagerStrategy: true,
    isRecoveryStrategy: true,
    recoveryTargetType: 'stop_loss_recoup',
    recoveryPhaseNotes: 'Couvre 64.8% du cylindre avec ajustement arithmétique modéré.',
    wagerTargetVolume: 14000,
    estimatedWagerTurnover: 140,
    vipTierTarget: 'Silver / Gold',
    gameConfig: {
      rouletteSector: 'dozens',
      rouletteDozens: [1, 2],
    },
    onWinAction: 'custom',
    onLossAction: 'increase_fixed',
    onLossValue: 0.10,
    stopOnProfit: 12.0,
    stopOnLoss: 18.0,
    maxBetLimit: 2.40,
    maxConsecutiveLosses: 5,
    evEstimate: -0.027,
    author: 'system',
    aiRationale: "Presque 2 coups sur 3 gagnants : comble les pertes de façon très fluide sans jamais mettre la bankroll en danger."
  },
  {
    id: 'strat-wager-rec-blackjack-basic',
    name: "🛡️ [WAGER RECOVERY] Blackjack Basic Strategy Bankroll Shield (99.43% RTP)",
    game: 'blackjack',
    description: "Application stricte du tableau de stratégie de base du Blackjack. Mises plates de 0.3% de la bankroll pour remonter la balance avec le plus faible house edge du casino (0.57%).",
    riskLevel: 'ultra_safe',
    baseBet: 0.30,
    currency: 'USDT',
    targetMultiplier: 2.00,
    winChance: 49.20,
    isWagerStrategy: true,
    isRecoveryStrategy: true,
    recoveryTargetType: 'bankroll_rebuild',
    recoveryPhaseNotes: 'Mises plates sur le jeu au meilleur RTP du casino.',
    wagerTargetVolume: 35000,
    estimatedWagerTurnover: 350,
    vipTierTarget: 'Diamant',
    gameConfig: {
      blackjackRule: 'standard',
    },
    onWinAction: 'reset',
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 12.0,
    stopOnLoss: 15.0,
    maxBetLimit: 1.20,
    maxConsecutiveLosses: 7,
    evEstimate: -0.0057,
    author: 'system',
    aiRationale: "Le meilleur jeu pour encaisser du volume tout en reconstruisant patiemment le capital après un stop loss."
  },
  {
    id: 'strat-wager-rec-keno-3num',
    name: "🛡️ [WAGER RECOVERY] Keno 3 Numéros Low Risk Anchor (1.50x)",
    game: 'keno',
    description: "Sélection de 3 numéros en risque Classique / Low. Encaissement dès 2 numéros sortis (cote 1.50x) avec mise constante pour stabiliser la balance.",
    riskLevel: 'low',
    baseBet: 0.40,
    currency: 'USDT',
    targetMultiplier: 1.50,
    winChance: 62.00,
    isWagerStrategy: true,
    isRecoveryStrategy: true,
    recoveryTargetType: 'stop_loss_recoup',
    recoveryPhaseNotes: '3 numéros choisis, retour dès 2 sorties.',
    wagerTargetVolume: 12000,
    estimatedWagerTurnover: 120,
    vipTierTarget: 'Silver',
    gameConfig: {
      kenoNumbers: [7, 14, 21],
      kenoRisk: 'low',
    },
    onWinAction: 'reset',
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 10.0,
    stopOnLoss: 14.0,
    maxBetLimit: 1.60,
    maxConsecutiveLosses: 5,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: "Variance lissée permettant d'ancrer le capital lors des phases de récupération."
  },
  {
    id: 'strat-wager-rec-wheel-low',
    name: "🛡️ [WAGER RECOVERY] Wheel 10-Segments Low Smooth Pivot (1.50x)",
    game: 'wheel',
    description: "Roue 10 segments Low Risk : 60% de probabilité de victoire à 1.50x. Mise plate avec cycle court pour effacer le déficit sans stress.",
    riskLevel: 'ultra_safe',
    baseBet: 0.40,
    currency: 'USDT',
    targetMultiplier: 1.50,
    winChance: 60.00,
    isWagerStrategy: true,
    isRecoveryStrategy: true,
    recoveryTargetType: 'wager_drawdown',
    recoveryPhaseNotes: '6 segments payants sur 10 à 1.50x.',
    wagerTargetVolume: 14000,
    estimatedWagerTurnover: 140,
    vipTierTarget: 'Bronze / Silver',
    gameConfig: {
      wheelSegments: 10,
      wheelRisk: 'low',
    },
    onWinAction: 'reset',
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 10.0,
    stopOnLoss: 14.0,
    maxBetLimit: 1.60,
    maxConsecutiveLosses: 4,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: "Taux de hit supérieur à la moyenne pour un redressement psychologique et financier rapide."
  },

  // --- NOUVELLES STRATÉGIES DE RÉCUPÉRATION À PETITES MISES (SPECTRE 25% À 60% WINRATE) ---
  {
    id: 'strat-wager-rec-dice-25pct-micro',
    name: "🎯 [WAGER RECOVERY] Dice 25% (3.96x) Micro-Mises Sniper (25% Win)",
    game: 'dice',
    description: "Stratégie de récupération à micro-mises (0.05 USDT / 0.05% de bankroll) sur une cote de 3.96x (25% de probabilité). Chaque victoire rapporte +2.96x la mise, ce qui permet de combler un stop-loss sans jamais risquer de gros montants sur un seul clic.",
    riskLevel: 'medium',
    baseBet: 0.05,
    currency: 'USDT',
    targetMultiplier: 3.96,
    winChance: 25.00,
    isWagerStrategy: true,
    isRecoveryStrategy: true,
    recoveryTargetType: 'stop_loss_recoup',
    recoveryPhaseNotes: 'Micro-mises sur cote 3.96x : 1 succès comble 3 pertes sans gonfler la mise.',
    wagerTargetVolume: 10000,
    estimatedWagerTurnover: 100,
    vipTierTarget: 'Silver / Gold',
    gameConfig: {
      diceCondition: 'above',
      diceTarget: 74.99,
    },
    onWinAction: 'reset',
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 15.0,
    stopOnLoss: 15.0,
    maxBetLimit: 0.50,
    maxConsecutiveLosses: 15,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: "Grâce au multiplicateur 3.96x, la mise de base peut être minuscule (0.05$) tout en délivrant des gains nets conséquents à chaque victoire."
  },
  {
    id: 'strat-wager-rec-limbo-3x-small',
    name: "🎯 [WAGER RECOVERY] Limbo 3.0x Micro-Rebound (33% Win)",
    game: 'limbo',
    description: "Multiplicateur cible 3.0x (33% probabilité) avec micro-mises de 0.08 USDT. Permet de compenser deux pertes par une victoire avec une mise de départ minime.",
    riskLevel: 'low',
    baseBet: 0.08,
    currency: 'USDT',
    targetMultiplier: 3.0,
    winChance: 33.00,
    isWagerStrategy: true,
    isRecoveryStrategy: true,
    recoveryTargetType: 'stop_loss_recoup',
    recoveryPhaseNotes: 'Petites mises à 3.0x pour une remontée progressive et sécurisée.',
    wagerTargetVolume: 12000,
    estimatedWagerTurnover: 120,
    vipTierTarget: 'Gold',
    gameConfig: {
      limboTarget: 3.0,
    },
    onWinAction: 'reset',
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 12.0,
    stopOnLoss: 14.0,
    maxBetLimit: 0.60,
    maxConsecutiveLosses: 10,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: "Permet de diviser par 5 le montant de la mise de départ comparé à une stratégie à 95% de winrate."
  },
  {
    id: 'strat-wager-rec-limbo-4x-bullet',
    name: "🎯 [WAGER RECOVERY] Limbo 4.0x Micro-Bullet (24.75% Win)",
    game: 'limbo',
    description: "Cote 4.0x (24.75% winrate) avec micro-mise fixe de 0.05 USDT. 1 victoire valide immédiatement +0.15 USDT net de profit, permettant d'effacer le drawdown sans mise lourde.",
    riskLevel: 'medium',
    baseBet: 0.05,
    currency: 'USDT',
    targetMultiplier: 4.0,
    winChance: 24.75,
    isWagerStrategy: true,
    isRecoveryStrategy: true,
    recoveryTargetType: 'stop_loss_recoup',
    recoveryPhaseNotes: 'Mise plate ultra-faible à 4.0x.',
    wagerTargetVolume: 9000,
    estimatedWagerTurnover: 90,
    vipTierTarget: 'Silver',
    gameConfig: {
      limboTarget: 4.0,
    },
    onWinAction: 'reset',
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 10.0,
    stopOnLoss: 12.0,
    maxBetLimit: 0.40,
    maxConsecutiveLosses: 16,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: "Idéal pour les joueurs préférant 20 petits tours à 0.05$ plutôt qu'un gros tour à 10$."
  },
  {
    id: 'strat-wager-rec-mines-3mines-35pct',
    name: "🎯 [WAGER RECOVERY] Mines 3-Mines 2-Gems (2.75x / 35% Win)",
    game: 'mines',
    description: "Grille 5x5 avec 3 mines. Découverte de 2 gemmes consécutives (cote 2.75x, ~35% de chances). Micro-mise de 0.08 USDT avec encaissement instantané dès 2 gemmes.",
    riskLevel: 'medium',
    baseBet: 0.08,
    currency: 'USDT',
    targetMultiplier: 2.75,
    winChance: 35.00,
    isWagerStrategy: true,
    isRecoveryStrategy: true,
    recoveryTargetType: 'stop_loss_recoup',
    recoveryPhaseNotes: '2 gemmes sur 3 mines à 2.75x avec micro-mise.',
    wagerTargetVolume: 11000,
    estimatedWagerTurnover: 110,
    vipTierTarget: 'Gold',
    gameConfig: {
      minesCount: 3,
      minesGemsToCashout: 2,
      minesChosenTiles: [0, 6],
    },
    onWinAction: 'reset',
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 12.0,
    stopOnLoss: 14.0,
    maxBetLimit: 0.60,
    maxConsecutiveLosses: 8,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: "Un gain de +175% par tirage réussi, neutralisant les pertes passées avec une exposition minimale."
  },
  {
    id: 'strat-wager-rec-crash-3x-micro',
    name: "🎯 [WAGER RECOVERY] Crash 3.0x Micro-Vol Rebuilder (33% Win)",
    game: 'crash',
    description: "Retrait automatique programmé à 3.00x sur Crash (33% winrate). Micro-mises plates de 0.06 USDT pour capitaliser +200% net par validation sans risquer la bankroll.",
    riskLevel: 'medium',
    baseBet: 0.06,
    currency: 'USDT',
    targetMultiplier: 3.00,
    winChance: 33.00,
    isWagerStrategy: true,
    isRecoveryStrategy: true,
    recoveryTargetType: 'stop_loss_recoup',
    recoveryPhaseNotes: 'Auto cashout fixe à 3.0x avec micro-mise.',
    wagerTargetVolume: 10000,
    estimatedWagerTurnover: 100,
    vipTierTarget: 'Silver / Gold',
    gameConfig: {
      crashAutoCashout: 3.00,
    },
    onWinAction: 'reset',
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 12.0,
    stopOnLoss: 15.0,
    maxBetLimit: 0.50,
    maxConsecutiveLosses: 10,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: "Chaque vol à 3.0x efface 2 pertes d'un coup, sans nécessiter de mise lourde."
  },
  {
    id: 'strat-wager-rec-roulette-single-dozen',
    name: "🎯 [WAGER RECOVERY] Roulette Simple Douzaine Sniper (3.0x / 32.4% Win)",
    game: 'roulette',
    description: "Mise ciblée sur 1 seule douzaine (12 numéros sur 37 = 32.43% de chances de gain à 3.0x). Micro-mise de 0.10 USDT pour un gain de +0.20 USDT net par coup gagnant.",
    riskLevel: 'medium',
    baseBet: 0.10,
    currency: 'USDT',
    targetMultiplier: 3.00,
    winChance: 32.43,
    isWagerStrategy: true,
    isRecoveryStrategy: true,
    recoveryTargetType: 'stop_loss_recoup',
    recoveryPhaseNotes: '1 douzaine payante à 3.0x avec micro-mises.',
    wagerTargetVolume: 11000,
    estimatedWagerTurnover: 110,
    vipTierTarget: 'Silver / Gold',
    gameConfig: {
      rouletteSector: 'dozens',
      rouletteDozens: [1],
    },
    onWinAction: 'reset',
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 12.0,
    stopOnLoss: 16.0,
    maxBetLimit: 0.80,
    maxConsecutiveLosses: 10,
    evEstimate: -0.027,
    author: 'system',
    aiRationale: "Offre un rapport gain/mise élevé permettant de garder une mise très petite."
  },
  {
    id: 'strat-wager-rec-dice-40pct-dalembert',
    name: "⚖️ [WAGER RECOVERY] Dice 40% (2.475x) D'Alembert Modéré (40% Win)",
    game: 'dice',
    description: "Cote intermédiaire 2.475x (40.0% probabilité). Petite mise de 0.10 USDT avec ajustement arithmétique très doux (+0.02u sur défaite, -0.02u sur victoire) pour un rétablissement équilibré.",
    riskLevel: 'low',
    baseBet: 0.10,
    currency: 'USDT',
    targetMultiplier: 2.475,
    winChance: 40.00,
    isWagerStrategy: true,
    isRecoveryStrategy: true,
    recoveryTargetType: 'stop_loss_recoup',
    recoveryPhaseNotes: 'Ajustement très progressif à 2.475x pour absorber les séries courtes.',
    wagerTargetVolume: 13000,
    estimatedWagerTurnover: 130,
    vipTierTarget: 'Gold',
    gameConfig: {
      diceCondition: 'above',
      diceTarget: 59.99,
    },
    onWinAction: 'custom',
    onLossAction: 'increase_fixed',
    onLossValue: 0.02,
    stopOnProfit: 12.0,
    stopOnLoss: 15.0,
    maxBetLimit: 0.80,
    maxConsecutiveLosses: 7,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: "Équilibre idéal entre fréquence de gain (40%) et rendement par victoire (x2.475)."
  },

  // =========================================================================
  // PRESETS SPECTRE LARGE (10% - 15% À 85% WINRATE) POUR TOUS LES ORIGINAUX
  // =========================================================================
  {
    id: 'strat-dice-10pct-sniper-preset',
    name: "🎯 Dice 10% Sniper Micro-Mises (9.90x / 10% Win)",
    game: 'dice',
    description: "Micro-mises (0.05 USDT) sur cote 9.90x (10% de chances). 1 seul gain compense 9 tours perdants et génère un bond net sans jamais doubler sur perte.",
    riskLevel: 'high',
    baseBet: 0.05,
    currency: 'USDT',
    targetMultiplier: 9.90,
    winChance: 10.00,
    gameConfig: {
      diceCondition: 'above',
      diceTarget: 89.99,
    },
    onWinAction: 'reset',
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 18.0,
    stopOnLoss: 12.0,
    maxBetLimit: 0.20,
    maxConsecutiveLosses: 30,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: "Cote 9.90x à 10% de probabilité : les micro-mises préservent le solde pendant les creux et débloquent un gain massif dès le premier coup gagnant."
  },
  {
    id: 'strat-dice-15pct-striker-preset',
    name: "🎯 Dice 15% Asymmetric Striker (6.60x / 15% Win)",
    game: 'dice',
    description: "Mises ultra-légères (0.06 USDT) sur cote 6.60x (15% de chances). 1 gain rapporte +5.6x la mise nette, idéal pour faire grossir le solde sans grosse mise.",
    riskLevel: 'medium',
    baseBet: 0.06,
    currency: 'USDT',
    targetMultiplier: 6.60,
    winChance: 15.00,
    gameConfig: {
      diceCondition: 'above',
      diceTarget: 84.99,
    },
    onWinAction: 'reset',
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 15.0,
    stopOnLoss: 14.0,
    maxBetLimit: 0.30,
    maxConsecutiveLosses: 22,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: "Winrate de 15% (cote 6.60x) : régularité satisfaisante avec 1 victoire tous les ~6.5 lancers en moyenne."
  },
  {
    id: 'strat-limbo-10x-deca-preset',
    name: "🎯 Limbo 10.0x Deca-Hunter Micro-Mises (9.9% Win)",
    game: 'limbo',
    description: "Micro-mises de 0.04 USDT ciblant le multiplicateur 10.0x (9.9% de probabilité). 1 seule victoire rapporte +9x la mise nette.",
    riskLevel: 'high',
    baseBet: 0.04,
    currency: 'USDT',
    targetMultiplier: 10.0,
    winChance: 9.90,
    gameConfig: {
      limboTarget: 10.0,
    },
    onWinAction: 'reset',
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 20.0,
    stopOnLoss: 10.0,
    maxBetLimit: 0.20,
    maxConsecutiveLosses: 35,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: "Multiplicateur 10x : la micro-mise permet d'encaisser de longs cycles et d'engranger de forts profits nets au déclenchement."
  },
  {
    id: 'strat-limbo-6x6-sniper-preset',
    name: "🎯 Limbo 6.6x Sniper Striker (15% Win)",
    game: 'limbo',
    description: "Cote 6.60x (15.0% de chances) avec micro-mises de 0.05 USDT. Un gain compense instantanément 6 tours et sécurise un surplus immédiat.",
    riskLevel: 'medium',
    baseBet: 0.05,
    currency: 'USDT',
    targetMultiplier: 6.60,
    winChance: 15.00,
    gameConfig: {
      limboTarget: 6.60,
    },
    onWinAction: 'reset',
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 15.0,
    stopOnLoss: 12.0,
    maxBetLimit: 0.25,
    maxConsecutiveLosses: 25,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: "Cote 6.60x à 15% de chances : profil sniper équilibré pour profiter d'une excellente espérance de gain unitaire."
  },
  {
    id: 'strat-mines-3m-4g-sniper-preset',
    name: "🎯 Mines 3-Mines 4-Diamants Sniper (6.80x / 12% Win)",
    game: 'mines',
    description: "Grille 3 mines, encaissement strict dès 4 diamants révélés (cote 6.80x, 12% de probabilité). Micro-mise de 0.05 USDT : un gain booste le profit net immédiatement.",
    riskLevel: 'high',
    baseBet: 0.05,
    currency: 'USDT',
    targetMultiplier: 6.80,
    winChance: 12.00,
    gameConfig: {
      minesCount: 3,
      minesGemsToCashout: 4,
      minesChosenTiles: [0, 6, 12, 18],
    },
    onWinAction: 'reset',
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 20.0,
    stopOnLoss: 12.0,
    maxBetLimit: 0.20,
    maxConsecutiveLosses: 30,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: "Cote 6.80x : la micro-mise absorbe facilement la variance et 1 round gagnant équivaut à 6.8x la mise."
  },
  {
    id: 'strat-mines-5m-2g-striker-preset',
    name: "🎯 Mines 5-Mines 2-Diamants (5.25x / 15.5% Win)",
    game: 'mines',
    description: "Grille 5 mines, 2 clics sécurisés pour une cote de 5.25x (15.5% de chances). Micro-mise de 0.06 USDT, gain net rapide sans martingaler.",
    riskLevel: 'medium',
    baseBet: 0.06,
    currency: 'USDT',
    targetMultiplier: 5.25,
    winChance: 15.50,
    gameConfig: {
      minesCount: 5,
      minesGemsToCashout: 2,
      minesChosenTiles: [4, 20],
    },
    onWinAction: 'reset',
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 15.0,
    stopOnLoss: 12.0,
    maxBetLimit: 0.25,
    maxConsecutiveLosses: 22,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: "Seulement 2 gemmes à découvrir avec 5 mines pour débloquer plus de 5x la mise."
  },
  {
    id: 'strat-crash-10x-rocket-preset',
    name: "🎯 Crash 10.0x Deca-Rocket (9.9% Win)",
    game: 'crash',
    description: "Auto-cashout programmé à 10.00x (9.9% de probabilité) avec micro-mises de 0.04 USDT. Rendement asymétrique maximal.",
    riskLevel: 'high',
    baseBet: 0.04,
    currency: 'USDT',
    targetMultiplier: 10.0,
    winChance: 9.90,
    gameConfig: {
      crashAutoCashout: 10.0,
    },
    onWinAction: 'reset',
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 20.0,
    stopOnLoss: 10.0,
    maxBetLimit: 0.20,
    maxConsecutiveLosses: 35,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: "Crash 10x : la micro-mise permet d'attendre la fusée sans entamer le capital et d'encaisser un x10 net."
  },
  {
    id: 'strat-crash-6x6-striker-preset',
    name: "🎯 Crash 6.60x Striker (15% Win)",
    game: 'crash',
    description: "Auto-cashout à 6.60x (15.0% de chances) avec micro-mises de 0.05 USDT. Un succès rapporte +5.6 unités nettes.",
    riskLevel: 'medium',
    baseBet: 0.05,
    currency: 'USDT',
    targetMultiplier: 6.60,
    winChance: 15.00,
    gameConfig: {
      crashAutoCashout: 6.60,
    },
    onWinAction: 'reset',
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 15.0,
    stopOnLoss: 12.0,
    maxBetLimit: 0.25,
    maxConsecutiveLosses: 25,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: "Cote 6.60x : profil d'auto-cashout intermédiaire rentable sans forcer sur la mise."
  },
  {
    id: 'strat-plinko-high-wings-preset',
    name: "🎯 Plinko 14 Rangées High Wings (10.5% Win - Multi 8x-55x)",
    game: 'plinko',
    description: "Plinko 14 rangées en risque Élevé : micro-mises fixes de 0.05 USDT calibrées pour absorber 200 lancers et attraper les coefficients d'ailes (8x à 55x).",
    riskLevel: 'high',
    baseBet: 0.05,
    currency: 'USDT',
    targetMultiplier: 8.0,
    winChance: 10.5,
    gameConfig: {
      plinkoRows: 14,
      plinkoRisk: 'high',
    },
    onWinAction: 'reset',
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 20.0,
    stopOnLoss: 12.0,
    maxBetLimit: 0.20,
    maxConsecutiveLosses: 40,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: "Les micro-mises permettent d'absorber les billes centrales et de générer un bond net dès l'atteinte des bacs latéraux."
  },
  {
    id: 'strat-keno-5num-sniper-preset',
    name: "🎯 Keno 5-Numbers Sniper (12% Win - 6.0x à 45x)",
    game: 'keno',
    description: "Sélection de 5 numéros Keno en risque Moyen. Gain à partir de 3 numéros (6.0x) jusqu'à 45x pour 5 hits. Micro-mises de 0.05 USDT.",
    riskLevel: 'high',
    baseBet: 0.05,
    currency: 'USDT',
    targetMultiplier: 6.0,
    winChance: 12.0,
    gameConfig: {
      kenoNumbers: [4, 11, 23, 31, 39],
      kenoRisk: 'medium',
    },
    onWinAction: 'reset',
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 18.0,
    stopOnLoss: 12.0,
    maxBetLimit: 0.20,
    maxConsecutiveLosses: 25,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: "Micro-mise de 0.05 USDT : chaque succès à 3+ numéros rapporte au moins 6x la mise."
  },
  {
    id: 'strat-roulette-corner-sniper-preset',
    name: "🎯 Roulette Carré Corner Sniper (8.80x - 10.8% Win)",
    game: 'roulette',
    description: "Pari sur 4 numéros adjacents (Carré / Corner, cote 8.80x, 10.8% de chances). Micro-mise de 0.05 USDT : un succès dégage un bond net immédiat.",
    riskLevel: 'high',
    baseBet: 0.05,
    currency: 'USDT',
    targetMultiplier: 8.80,
    winChance: 10.8,
    gameConfig: {
      rouletteSector: 'corner',
      rouletteNumbers: [16, 17, 19, 20],
    },
    onWinAction: 'reset',
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 18.0,
    stopOnLoss: 10.0,
    maxBetLimit: 0.20,
    maxConsecutiveLosses: 30,
    evEstimate: -0.027,
    author: 'system',
    aiRationale: "Cote 8.80x : 1 gain compense 8 tours sans martingaler."
  },
  {
    id: 'strat-roulette-sixain-sniper-preset',
    name: "🎯 Roulette Sixain Transversale (5.90x - 16.2% Win)",
    game: 'roulette',
    description: "Pari sur 6 numéros (Sixain, cote 5.90x, 16.2% de chances). Micro-mise de 0.06 USDT pour des gains asymétriques.",
    riskLevel: 'medium',
    baseBet: 0.06,
    currency: 'USDT',
    targetMultiplier: 5.90,
    winChance: 16.2,
    gameConfig: {
      rouletteSector: 'sixain',
      rouletteNumbers: [13, 14, 15, 16, 17, 18],
    },
    onWinAction: 'reset',
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 15.0,
    stopOnLoss: 12.0,
    maxBetLimit: 0.30,
    maxConsecutiveLosses: 20,
    evEstimate: -0.027,
    author: 'system',
    aiRationale: "Cote 5.90x à 16.2% de chances : excellent compromis entre couverture et gain net."
  },
  {
    id: 'strat-hilo-4cards-sniper-preset',
    name: "🎯 Hilo 4-Cards Chain Sniper (7.20x - 12.5% Win)",
    game: 'hilo',
    description: "Enchaînement de 4 cartes consécutives pour une cote de 7.20x (12.5% de chances). Micro-mise de 0.05 USDT.",
    riskLevel: 'high',
    baseBet: 0.05,
    currency: 'USDT',
    targetMultiplier: 7.20,
    winChance: 12.5,
    gameConfig: {
      hiloStartCard: 6,
    },
    onWinAction: 'reset',
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 18.0,
    stopOnLoss: 10.0,
    maxBetLimit: 0.20,
    maxConsecutiveLosses: 25,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: "Cote 7.20x : multiplicateur explosif avec micro-mise."
  },
  {
    id: 'strat-wheel-20seg-sniper-preset',
    name: "🎯 Wheel 20 Segments Medium (9.90x - 10% Win)",
    game: 'wheel',
    description: "Roue 20 segments : micro-mises de 0.05 USDT sur les segments à 9.90x (10% de chances).",
    riskLevel: 'high',
    baseBet: 0.05,
    currency: 'USDT',
    targetMultiplier: 9.90,
    winChance: 10.0,
    gameConfig: {
      wheelSegments: 20,
      wheelRisk: 'medium',
    },
    onWinAction: 'reset',
    onLossAction: 'reset',
    onLossValue: 1.0,
    stopOnProfit: 18.0,
    stopOnLoss: 10.0,
    maxBetLimit: 0.20,
    maxConsecutiveLosses: 30,
    evEstimate: -0.01,
    author: 'system',
    aiRationale: "Cote 9.90x : un gain nettoie immédiatement plusieurs tours perdants."
  },

  // ==========================================
  // STAKE.COM DICE AUTOMATED MULTI-CONDITIONS (4 À 30 CONDITIONS)
  // ==========================================
  generateStakeDiceMultiConditionStrategy(100, 'USDT', 6, 'anti_streak'),
  generateStakeDiceMultiConditionStrategy(100, 'USDT', 12, 'oscillator'),
  generateStakeDiceMultiConditionStrategy(100, 'USDT', 18, 'tactical_matrix'),
  generateStakeDiceMultiConditionStrategy(100, 'USDT', 24, 'vip_volume'),
  generateStakeDiceMultiConditionStrategy(100, 'USDT', 30, 'master_30'),
];


